translation part 5
FreeCodeCampChina/challenges pull request #1
Opened 2018-07-19 01:46 UTC by ifyour

翻译 `API 和微服务 -- NPM` 部分.

变更文件: 

- [x] managing-packages-with-npm.json

完成进度: 

- [ ] 10%

2018-07-19 21:42 UTC, S1ngS1ng requested changes
@huluoyang 
1. 建议调整一下 wiki 中文件的顺序。那些注明了“实战”的，先翻译可能会更好。
2. 我觉得，`testString` 字段也是要翻译的，但不是翻译全部，只需要翻译 `assert(first, second)` 中，第二个参数 `second` 就行，因为这个是控制台输出。
详情参考 [我在 curriculum-cn 里的这条评论](https://github.com/FreeCodeCampChina/curriculum-cn/pull/10/files/607b18c2401a258384cc4e2f2347e6439e97d664#r201791845)

@ifyour 里面提到的大部分是建议，你来决定改不改吧，但格式、上下文统一的问题，还是建议你改下

-------

Update: `assert` typo fix 🤦‍♂️

2018-07-19 21:42 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "如果你转到之前设置的 Glitch 项目并查看屏幕左侧，你会找到看到一个文件树，你可以在其中查看项目中各种文件的概述。 在文件树的末尾部分，你会看到 package.json - 我们将在接下来的几个挑战中改进这个文件。",
注意，这里的 Glitch 不是项目名字，而是一个平台：https://glitch.com/
请参考 [这里](https://github.com/FreeCodeCampChina/challenges/blob/translate/05-apis-and-microservices/apis-and-microservices-projects.json#L11-L13)，或点击 [这个页面](https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm/) 中 "Go to the first lesson" 上一行的 "this link"

@huluoyang 参考 Review 评论的建议

---------

`你会找到看到一个文件树` =>
`你会看到一个文件树`

---------

`……你可以在其中查看项目中各种文件的概述。 在文件树的末尾部分……`

请删除全角句号之后的空格。下同

2018-07-19 21:42 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "author 字段",
尽管原文没有，但个人觉得最后加个冒号可能会更好，下同。你来决定吧

2018-07-19 21:42 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "package.json 是任何 Node.js 项目或 NPM 包的中心。它存储项目的相关信息，就像 HTML 文档中的 <head>-section 描述网页内容一样。 package.json 由单个 JSON 对象组成，它以键值对的形式存储项目的信息。 一个最小的 package.json 文件至少包含两个必须字段：name 和 version -- 但是提供有关项目的
原文：`just like the <head>-section in a HTML document describes the content of a webpage`
建议翻译：`就像 HTML 文档中的 <head> 区域是用来描述网页的通用信息（元信息）一样`

参考：https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/head
另外，讲道理，说 “`<head>` 是用来描述网页内容” 有些不准确，`<body>` 才是吧。

------

`……它以键值对的形式存储项目的信息。 一个最小的 package.json ……`

全角句号之后不需要再加空格了。参考规范第四条

--------

version 之后，如果你需要使用破折号，应该是 `—`，macos 上可以用 <kbd>shift</kbd> + <kbd>option</kbd> + <kbd>-</kbd> 打出。请参考这个截图，
![image](https://user-images.githubusercontent.com/13592559/42960053-98e93458-8b3f-11e8-8fe2-c998c253fec0.png)
破折号应该是 em dash，而不是两个 en dash。你采用的是两个 en dash。详情参考 [wikipedia 破折号](https://zh.wikipedia.org/wiki/%E7%A0%B4%E6%8A%98%E5%8F%B7)

2018-07-19 21:42 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "这个文件中最常见的信息之一是作者字段，它指定了谁是项目的创建者。它可以是字符串，也可以是带有联系人详细信息的对象。对于较大的项目，建议使用对象，但是在我们的例子中，一个简单的字符串就可以了，比如下面的例子。",
`作者字段` 建议改成 `author 字段`，或 `作者（author）字段`

请尽量保持统一，比如你在后文就采用了 `author 字段` 这样的表达方式

2018-07-19 21:42 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "将你的名字添加到 Glitch 项目的 package.json 中的 author 字段中。",
`将你的名字添加到 Glitch 项目的 package.json 中的 author 字段中。`
可以改成：
`将你的名字添加到 Glitch 项目中，package.json 的 author 字段。`

2018-07-19 21:42 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "如果你计划将来把这个包发布到 NPM, 请记住这是描述信息，当用户决定是否安装你的包时，应该将这个项目的想法告诉他们。 然而，这并不是描述信息的唯一使用场景: 它也是总结项目的一种很好的方式, 对于一个普通的 Node.js 项目来说，帮助其它开发者甚至是你自己快速的理解项目这非常重要。",
`npm` 不应该大写，请参阅 [官网](https://www.npmjs.com/)

-------

`请记住这是描述信息，当用户决定是否安装你的包时，应该将这个项目的想法告诉他们。 ` 建议改成：
`请注意 description 字段的作用是告知用户这个包的用途，这样用户就可以决定是否要安装你发布的包。`

个人建议，在不 啰嗦/重复/冗长 的前提下，尽量把 `this` 之类的指示代词补充完整，读起来会更符合中文的表达习惯。
对于一句话中的相同主语，或者**翻译中**已经出现过的内容，就可以不补充，比如这两句话（来自 [wikipedia 的 JavaScript 词条](https://en.wikipedia.org/wiki/JavaScript) ）：
```
JavaScript often abbreviated as JS, is a high-level, interpreted programming language. It is a language which is also characterized as dynamic, weakly typed, prototype-based and multi-paradigm.
```
  翻译成：
```
JavaScript，通常缩写为 JS，是一种高级的解释型语言，它还具有动态、弱类型和基于原型的特点，并支持多种编程范式。
``` 

  就足够了，不必要再在每个逗号之后补充主语。需要注意的是，英语与汉语对于逗号和句号的使用是略有区别的。比较常见的情况是，英语中句号分隔的多个句子翻译成汉语变成了一句。

@huluoyang 如果需要，可以考虑加到翻译指南

-------

`帮助其它开发者甚至是你自己快速的理解项目这非常重要。` 建议改成：
`它可以帮助其它开发者、未来的维护者以及你自己快速地了解项目，这同样非常重要。`

原句不是很通顺。另外请注意 `的、地、得` 的区别。 
@huluoyang 可以考虑加到翻译指南
以及，个人认为这里的 `understand` 应该翻译成“了解”，而不是“理解”，毕竟只是一个 `description`。。你来决定用哪个吧

2018-07-19 21:42 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "正如你所见，这个字段的结构是一个包含双引号字符串的数组。",
`包含双引号字符串的数组` 建议改成：
`由双引号字符串组成的数组`

2018-07-19 21:42 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "license 字段是你告知用户你的项目允许用在什么地方。",
原文 `The license-field is where you inform users of your project what they are allowed to do with it.`
这是一个复杂句，整体上是一个 `where` 引导的表语从句（predictive clause）里面嵌套了一个 `what` 引导的宾语从句。
注意理清每个部分之间的关系，以及 `they` 和 `it` 的指代。最后的 `it` 指代的是项目（project），`they` 指代的是用户，因此这里要表达的是：`告知用户，（让他们知道）他们可以如何使用这个项目`（what to do），而不是告知他们用在什么地方（where to use）

因此这里应该翻译成：
`license 字段是你告知用户应该如何使用项目的地方。`

2018-07-19 21:42 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "开源项目的一些常用许可证包括 MIT 和 BSD。如果你想了解更多适合你项目的许可证的信息，那么 http://choosealicense.com 是一个不错的网站。",
习惯上，不说“开源许可证”，而应该是“开源许可”、“开源协议”。下同。

参考 [wikipedia 上的 许可](https://zh.wikipedia.org/wiki/%E6%8E%88%E6%AC%8A_(%E6%B3%95%E5%BE%8B))：
![image](https://user-images.githubusercontent.com/13592559/42971351-cacc14a6-8b60-11e8-8f79-3ad03aa7b975.png)

这里建议调整一下语序，变成：`常见的开源协议是 MIT 和 BSD。`

2018-07-19 21:42 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "许可证信息并不是必须的。大多数国家的版权法会默认让你拥有自己创作的作品的所有权。 但是，明确说明用户可以做什么和不能做什么始终是一个很好的做法。",
`始终是` 建议改成 `一直都是` 或者 `会是`

2018-07-19 21:42 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "使用包管理器的最大原因之一是它们强大的依赖管理特性。在新的计算机上开始一个项目时，不用手动确认你已安装所有的依赖，npm 会自动为你安装它们。但是 npm 如何准确的知道你项目需要哪些依赖呢？ 我们来看看 package.json 中 dependencies 这一部分。",
请删去全角问号之后的空格

2018-07-20 04:37 UTC, huluoyang commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "package.json 是任何 Node.js 项目或 NPM 包的中心。它存储项目的相关信息，就像 HTML 文档中的 <head>-section 描述网页内容一样。 package.json 由单个 JSON 对象组成，它以键值对的形式存储项目的信息。 一个最小的 package.json 文件至少包含两个必须字段：name 和 version -- 但是提供有关项目的
我也是看了 wikipedia 才知道原来中文破折号来自于英文破折号：em dash。
en dash 也就是我们常用的连接符，这确实是2个完全的符号，感谢@S1ngS1ng。

2018-07-20 04:40 UTC, ifyour commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "package.json 是任何 Node.js 项目或 NPM 包的中心。它存储项目的相关信息，就像 HTML 文档中的 <head>-section 描述网页内容一样。 package.json 由单个 JSON 对象组成，它以键值对的形式存储项目的信息。 一个最小的 package.json 文件至少包含两个必须字段：name 和 version -- 但是提供有关项目的
学习了

2018-07-20 05:23 UTC, huluoyang commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "license 字段是你告知用户你的项目允许用在什么地方。",
作为一个英文小白，当我看到这么详细的分析时，真的是热泪盈眶，我的英文老师也这样多好。
@S1ngS1ng 的分析大体是对的，但有一处有误。
`如何使用和(what to do)并不符合，如何使用应该对应(how to use)`
把这句话一分为二：
`The license-field is where you inform users of your project.`
license 字段是你告知你的项目使用者的地方。（告知什么内容呢？后面会细说）
`what they are allowed to do with it.`
允许他们拿这个项目干什么？
合而为一：
`license 字段是你告知你的项目使用者允许他们拿这个项目干什么的地方。`
简化如下：
`项目使用者=>用户`
`你的=>省略（废话，不是我的项目会是谁的项目）`
总结：
`license 字段是你告知用户允许他们拿这个项目干什么的地方。`

2018-07-20 05:27 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "license 字段是你告知用户你的项目允许用在什么地方。",
@huluoyang 嗯嗯，是这个意思！ 😂  确实，上面我写的不够标准。。

2018-07-20 15:04 UTC, ifyour commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "如果你转到之前设置的 Glitch 项目并查看屏幕左侧，你会找到看到一个文件树，你可以在其中查看项目中各种文件的概述。 在文件树的末尾部分，你会看到 package.json - 我们将在接下来的几个挑战中改进这个文件。",
> 只需要翻译 aseert(first, second) 中

这里有一处拼写错误

`aseert` => `assert` 

🤓

2018-07-20 16:29 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "如果你转到之前设置的 Glitch 项目并查看屏幕左侧，你会找到看到一个文件树，你可以在其中查看项目中各种文件的概述。 在文件树的末尾部分，你会看到 package.json - 我们将在接下来的几个挑战中改进这个文件。",
@ifyour 谢谢。找了半天才找到你说的部分 😂 
应该到外面评论的，这里是 code diff 的 comment。如果在 review 之后，你 commit 了相关行代码的改动，这里就会默认折叠 🌝

2018-07-20 16:33 UTC, S1ngS1ng approved these changes
LGTM 👍

2018-07-21 10:03 UTC, ifyour commented
这一部分参考了[语义化版本控制规范（SemVer）](https://semver.org/lang/zh-CN/)的翻译

2018-07-21 21:58 UTC, S1ngS1ng requested changes
@huluoyang 看下 line#192 的评论

@ifyour 一些小问题，大部分是建议，你考虑下吧

2018-07-21 21:58 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "在 package.json 中，dependencies 这部分的 npm 包的版本号遵循所谓的语义化版本（SemVer），它是一种软件版本控制的行业标准，旨在使管理依赖项更加容易。在 npm 上发布的库、框架或其它工具都应该使用语义化版本（SemVer），以便可以清楚的告知用户，项目的依赖包在更新时可以预期的变化。",
`以便可以清楚的告知用户，项目的依赖包在更新时可以预期的变化。` 建议：

`以便让使用该依赖包的用户能够在依赖包需要升级时，提前规划自己的项目需要为之做出的改动。`

或者，如果你有更好的说法也行

2018-07-21 21:58 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "在没有公共 API 的项目中，语义化版本（SemVer）没有意义 —— 除非你的项目与上面的例子类似，否则请使用其它的版本控制格式吧。",
注意，破折号两边应该是不需要额外空格的

--------

`版本控制格式` 建议 =>
`版本控制方式` 或 `版本控制工具`

2018-07-21 21:58 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "在开发使用外部依赖项的软件（大多数情况都是这样）时，了解语义化版本（SemVer）会很有用。有一天你会明白这些数字的含义，在项目中它可以避免你意外地引入一些重大更改，同时也能避免“昨天还是好好的”今天就不工作了这种情况发生。",
个人认为，`breaking changes` 翻译成 `非向下兼容的更改` 或 `非向前兼容的更改` 应该会更确切。
我的理解是，主观意义上认为的“重大”不一定是 `breaking changes`；反之，小的改动也可以成为 `breaking changes`。
另一方面，SemVer 的出现即是基于这种情景，而且它对版本号的定义也是基于此。它不允许 breaking changes 出现在 minor 与 patch increment，只有 major 可以。

所以，原文说的 `save you from accidentally introducing breaking changes`，我认为是 “非向下兼容的更改”

参考：https://en.wikipedia.org/wiki/Backward_compatibility

-------------

`同时也能避免“昨天还是好好的”今天就不工作了这种情况发生。` =>
`同时也能避免“昨天还能好好的运行，今天就不行了”这种情况发生。`

1. 引号貌似不太对
2. `工作` 不是很好，这里要表述的意思是“程序运行”。尽管，对应回英文都是 `work`

2018-07-21 21:58 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "版本格式：主版本号.次版本号.修订号，版本号递增规则如下：",
建议 `<code>主版本号.次版本号.修订号</code>`

2018-07-21 21:58 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "主版本号：当你做了不兼容的 API 修改，",
`当你做了不兼容的 API 修改，` =>
`当你做了不向下兼容的公共 API 修改，`

2018-07-21 21:58 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "次版本号：当你做了向下兼容的功能性新增，",
`当你做了向下兼容的功能性新增` =>

`当你添加了向下兼容的新功能`

2018-07-21 21:58 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "在最后一个挑战中，我们告诉 npm 只包含特定版本的依赖包。如果想让项目各个部分保持相互兼容，冻结依赖是一个有效的办法。但是大多数情况下，我们并不希望错过依赖项的问题修复，因为它们通常包含重要的安全补丁，并且希望这样可以持续正常的工作。",
`冻结依赖` => 改成

`定死依赖版本` 会不会好些？

---------

`并且希望这样可以持续正常的工作。` =>

`而且它们理论上也不该不兼容我们既有的代码。` 

因此，应该翻译成：=>

`而且它们理论上也会兼容我们既有的代码。`

2018-07-21 21:58 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "为了让 npm 依赖项更新到最新的修订版，你可以在依赖包的版本号前加一个波浪号（~）。在 package.json 中，我们当前的 moment 依赖包更新规则是：仅使用特定版本（2.10.2），但我们想用它最新的 2.10.x 版本。",
@huluoyang 这里，有没有必要多说一句，“英文的波浪号” 或者 “半角波浪号”？

2018-07-21 21:58 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "<code>\"some-package-name\": \"~1.3.8\" 可以更新到任何 1.3.x 版本。</code>",
`可以更新到任何 1.3.x 版本。` =>

`是定义这个包允许使用的版本为 1.3.x。`

2018-07-22 01:56 UTC, ifyour commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "为了让 npm 依赖项更新到最新的修订版，你可以在依赖包的版本号前加一个波浪号（~）。在 package.json 中，我们当前的 moment 依赖包更新规则是：仅使用特定版本（2.10.2），但我们想用它最新的 2.10.x 版本。",
感觉`英文的波浪号`这样更严谨点 😁

2018-07-22 02:00 UTC, ifyour commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "在最后一个挑战中，我们告诉 npm 只包含特定版本的依赖包。如果想让项目各个部分保持相互兼容，冻结依赖是一个有效的办法。但是大多数情况下，我们并不希望错过依赖项的问题修复，因为它们通常包含重要的安全补丁，并且希望这样可以持续正常的工作。",
`定死依赖版本` => `锁定定依赖包版本`

这样会不会更书面化一点？😂

2018-07-22 09:34 UTC, S1ngS1ng approved these changes
记得改一下，`锁定定依赖包版本` => `锁定依赖包版本`

别的没问题。LGTM 👍

2018-07-22 09:34 UTC, S1ngS1ng commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "在最后一个挑战中，我们告诉 npm 只包含特定版本的依赖包。如果想让项目各个部分保持相互兼容，锁定定依赖包版本是一个有效的办法。但是大多数情况下，我们并不希望错过依赖项的问题修复，因为它们通常包含重要的安全补丁，而且它们理论上也会兼容我们既有的代码。",
`锁定定依赖包版本` => `锁定依赖包版本`

2018-07-24 06:50 UTC, huluoyang commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "为了让 npm 依赖项更新到最新的修订版，你可以在依赖包的版本号前加一个波浪号（~）。在 package.json 中，我们当前的 moment 依赖包更新规则是：仅使用特定版本（2.10.2），但我们想用它最新的 2.10.x 版本。",
我觉得波浪号就挺好，加其它修饰都显得多余。

2018-07-24 07:10 UTC, huluoyang requested changes
部分翻译有待修改，离成功只有一个一步之遥了，加油。

2018-07-24 07:10 UTC, huluoyang commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "删除 dependencies 中的 moment 依赖包。",
删除 dependencies 中的 moment 依赖包。
dependencies 本身就是依赖的意思，上文意思有重复，不够简洁。
建议修改成：删除 moment 依赖包。

2018-07-24 07:10 UTC, huluoyang commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "删除依赖包后，确保有正确数量的逗号。"
如果删除操作是最后一行，就会有多余的逗号。
所以这里建议修改成：删除依赖包后，确保没有多余的逗号。

2018-07-24 07:10 UTC, huluoyang commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +          "text": "\"dependencies\" 未包含 \"moment\"",
未包含 => 不包含

2018-07-24 07:10 UTC, huluoyang commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "此刻，你项目中的 moment 依赖包的版本应该是 ~2.10.2，这意味着 npm 可以安装 2.10.x 版的 moment，如果使用脱字符（^）来替换版本号的前缀，那么 npm 可以安装的版本则是 2.x.x。",
caret 建议翻译成插入符号，而不是脱字符。

2018-07-24 07:10 UTC, huluoyang commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +        "为了让 npm 依赖项更新到最新的修订版，你可以在依赖包的版本号前加一个英文的波浪号（~）。在 package.json 中，我们当前的 moment 依赖包更新规则是：仅使用特定版本（2.10.2），但我们想用它最新的 2.10.x 版本。",
tilde-character 建议统一翻译成：波浪符号，其他地方同理。

2018-07-24 07:10 UTC, huluoyang commented on 05-apis-and-microservices/managing-packages-with-npm.json
> +          "testString": "getUserInput => $.get(getUserInput('url') + '/_api/package.json').then(data => { var packJson = JSON.parse(data); assert.notProperty(packJson.dependencies, 'moment', '\"depen
任然有 => 仍然有

2018-07-28 08:43 UTC, huluoyang commented
🎉 恭喜明明成功完成第一个任务，Mission is impossible!

2018-07-28 08:43 UTC, merged