完成“面试前期准备-算法-Symmetric Difference”
FreeCodeCampChina/challenges pull request #10
Opened 2018-07-22 03:42 UTC by leejay1992

Symmetric Difference：对称差算法。

2018-07-22 23:55 UTC, S1ngS1ng requested changes
1. 所有的 markdown 语法都要改成 HTML 语法才行
2. 建议采用 JavaScript 的语法举例
3. 题目的描述，特别是有多个参数的时候，建议分开描述。先解释传入的每个参数的意义，然后再细致地描述题目逻辑。可以参考我的翻译：
    - [Diff Two Arrays](https://github.com/FreeCodeCampChina/challenges/pull/11/files#diff-10077b5d43aefc399fb6f9c6541a20d6R73)
    - [Seek and destroy](https://github.com/FreeCodeCampChina/challenges/pull/11/files#diff-10077b5d43aefc399fb6f9c6541a20d6R174)

2018-07-22 23:55 UTC, S1ngS1ng commented on 08-coding-interview-prep/algorithms.json
> +        "知识提要：对称差 (Symmetric Difference)，数学上，两个 <a href='https://baike.baidu.com/item/%E9%9B%86%E5%90%88/2908117' target='_blank'>集合</a> 的对称差是只属于其中一个集合，而不属于另一个集合的元素组成的集合，例如：集合 A = { 1, 2, 3} 和 B = {
建议把 `对称差` 的链接放到前面。

`知识提要：<a href='https://baike.baidu.com/item/%E5%AF%B9%E7%A7%B0%E5%B7%AE' target='_blank'>对称差</a>（Symmetric Difference）。
`

-------

既然是 JavaScript 平台，建议用 `[1, 2, 3]` 来表示数组。下同

2018-07-22 23:55 UTC, S1ngS1ng commented on 08-coding-interview-prep/algorithms.json
> +        "创建一个函数sym，输入两个或两个以上的数组作为参数，然后返回值为 **对称差** 的数组",
`然后返回值为 **对称差** 的数组` => `以数组的形式返回它们的对称差。`

注意，这里用 markdown syntax 是不行的。如果要强调，也许要用 `<em>` 或者 `<b>` 这样的包裹起来

下同

2018-07-22 23:55 UTC, S1ngS1ng commented on 08-coding-interview-prep/algorithms.json
> +        "如果你遇到了困难，请点击 <a href='http://forum.freecodecamp.org/t/how-to-get-help-when-you-are-stuck/19514' target='_blank'>帮助</a>。请尽量编写属于你自己的代码。尝试一下 **结对编程** 会有意料不到的惊喜哦。",
见群内讨论

以及： https://github.com/FreeCodeCampChina/challenges/pull/8/files#diff-7f72cbe6be2fd7054b07b7455775fde6R16

2018-07-22 23:55 UTC, S1ngS1ng commented on 08-coding-interview-prep/algorithms.json
> +          "testString": "assert.sameMembers(sym([1, 2, 3], [5, 2, 1, 4]), [3, 4, 5], '<code>sym([1, 2, 3], [5, 2, 1, 4])</code>的返回值应该是<code>[3, 4, 5]</code>。');"
这两行，`<code>` 周围要有空格。但 `</code>。` 不需要

2018-07-22 23:55 UTC, S1ngS1ng commented on 08-coding-interview-prep/algorithms.json
> +        "比较和更新存储在 <a href='https://baike.baidu.com/item/%E4%BA%8C%E7%BB%B4%E6%95%B0%E7%BB%84' target='_blank'>2D数组 </a>中的库存，并将其与新交付的第二个2D数组进行比较。更新当前的库存项数量（arr1）。如果找不到项目，请将新项目和数量添加到库存数组中。返回的库存数组应该按照项目
`2D数组` => `二维数组`

------

建议更新题目描述，见 review comments

2018-07-23 04:40 UTC, S1ngS1ng commented
@bigfacemaster 另外，你添加了 `.DS_Store` 文件。请删除

2018-07-24 17:07 UTC, S1ngS1ng requested changes
空格改一下。之前的 comments 也看一下，你还都没改。先别添加新的翻译内容了

2018-07-24 17:07 UTC, S1ngS1ng commented on 08-coding-interview-prep/algorithms.json
> +          "text": "<code>permAlone(\"aab\")</code> 应该返回 2 。",
半角字符与全角标点之间不应该添加空格。见群内讨论

所以这里是 `应该返回 2。`
下同

2018-07-24 17:07 UTC, S1ngS1ng commented on 08-coding-interview-prep/algorithms.json
> +        "如果你遇到了困难，请点击 <a href='http://forum.freecodecamp.org/t/how-to-get-help-when-you-are-stuck/19514'target='_blank'> 帮助 </a>。你可以找人 “结对编程”，但不要因此放弃思考。",
见群内讨论。行内元素是否加空格取决于里面的内容。
中文引号两边也是不需要加空格的

`如果你遇到了困难，请点击<a href='http://forum.freecodecamp.org/t/how-to-get-help-when-you-are-stuck/19514'target='_blank'>帮助</a>。你可以找人“结对编程”，但不要因此放弃思考。`

2018-07-24 18:02 UTC, huluoyang requested changes

2018-07-24 18:02 UTC, huluoyang commented on 08-coding-interview-prep/algorithms.json
> +        "知识提要：对称差 (Symmetric Difference)，数学上，两个 <a href='https://baike.baidu.com/item/%E9%9B%86%E5%90%88/2908117'target='_blank'> 集合 </a> 的对称差是只属于其中一个集合，而不属于另一个集合的元素组成的集合，例如：集合 A = { 1, 2, 3} 和 B = {
Symmetric Difference => 对称差分

2018-07-24 18:27 UTC, S1ngS1ng commented on 08-coding-interview-prep/algorithms.json
> +        "知识提要：对称差 (Symmetric Difference)，数学上，两个 <a href='https://baike.baidu.com/item/%E9%9B%86%E5%90%88/2908117'target='_blank'> 集合 </a> 的对称差是只属于其中一个集合，而不属于另一个集合的元素组成的集合，例如：集合 A = { 1, 2, 3} 和 B = {
@huluoyang https://zh.m.wikipedia.org/zh-hans/对称差

2018-07-29 16:33 UTC, S1ngS1ng requested changes
@BigFaceMaster 之前的 comments 你还没有改，点开 Show outdated 看下。
比如数组的表示方式，markdown syntax 要删掉，以及`<a>`标签里面其实不需要加空格。
麻烦你更新下哈。内容方面应该没有问题了

2018-07-31 12:49 UTC, BigFaceMaster commented
已经根据建议 ，更改并优化。

2018-07-31 16:36 UTC, S1ngS1ng approved these changes
LGTM. Thanks 👍

2018-08-02 20:36 UTC, huluoyang requested changes

2018-08-02 20:36 UTC, huluoyang commented on 08-coding-interview-prep/algorithms.json
> +        "知识提要：<a href='https://baike.baidu.com/item/%E5%AF%B9%E7%A7%B0%E5%B7%AE'target='_blank'>对称差 (Symmetric Difference)</a>，数学上，两个 <a href='https://baike.baidu.com/item/%E9%9B%86%E5%90%88/2908117'
知识提要👍
对称查分 => 对等查分

2018-08-02 20:36 UTC, huluoyang commented on 08-coding-interview-prep/algorithms.json
> +        "比较和更新存储在<a href='https://baike.baidu.com/item/%E4%BA%8C%E7%BB%B4%E6%95%B0%E7%BB%84'target='_blank'>二维数组</a>中的库存，并将其与新交付的第二个二维数组进行比较。更新当前的库存项数量（arr1）。如果找不到项目，请将新项目和数量添加到库存数组中。返回的库存数组应该按照项目的字母
符号使用混乱，行文不够流畅。
请重新翻译。

2018-08-06 03:37 UTC, S1ngS1ng requested changes
@BigFaceMaster 内容上没啥大问题。但其他部分，不翻译的/不需要改的部分就不要改，保持和原文一样就行，否则后续很难做 diff。

格式问题记得参考 style-guide

2018-08-06 03:37 UTC, S1ngS1ng commented on 08-coding-interview-prep/algorithms.json
> +        "知识提要：<a href='https://baike.baidu.com/item/%E5%AF%B9%E7%A7%B0%E5%B7%AE'target='_blank'>对称差 (Symmetric Difference)</a>，数学上，两个 <a href='https://baike.baidu.com/item/%E9%9B%86%E5%90%88/2908117'
`两个 <a href='https://baike.baidu.com/item/%E9%9B%86%E5%90%88/2908117'target='_blank'>集合</a> 的对称差分是只属于其中一个集合，`

由于 `<a>` 里面和外面都是全角，因此 `<a>` 两边不需要加空格。

-------

最后哪个 `</code>` 之后多了一个半角逗号。

2018-08-06 03:37 UTC, S1ngS1ng commented on 08-coding-interview-prep/algorithms.json
> +        "思路：设定两个数组 (例如：<code>let A = [1, 2, 3]</code>，<code>let B = [2, 3, 4]</code>，)作为参数传入，返回对称差分数组（<code>A &xutri; B = C = [1, 4]</code>），且数组元素具有唯一性（没有重复项）。",
第一个括号里面，`）` 之前不应该加逗号

-------

`且数组元素具有唯一性（没有重复项）。` =>
`且数组中没有重复项。`

2018-08-06 03:37 UTC, S1ngS1ng commented on 08-coding-interview-prep/algorithms.json
> +        "如果你遇到了困难，请点击 <a href='http://forum.freecodecamp.org/t/how-to-get-help-when-you-are-stuck/19514'target='_blank'>帮助</a>。你可以找人“结对编程”，但不要因此放弃思考。",
同理，这里的 “帮助” 之前也不需要加空格。
但引号前是要加的。参考 style-guide

![image](https://user-images.githubusercontent.com/13592559/43695642-ae67995c-98ee-11e8-93f1-a42ed3947453.png)

2018-08-06 03:37 UTC, S1ngS1ng commented on 08-coding-interview-prep/algorithms.json
> +        "创建一个<a href='https://baike.baidu.com/item/%E4%BA%8C%E7%BB%B4%E6%95%B0%E7%BB%84'target='_blank'>二维数组</a>，比较并更新存储在<code>二维数组</code>中的”库存“元素，然后并将其与新产生的第二个二维数组进行对比，更新当前的”库存“项的数量（<code>arr1</code
这里的第一组引号好像用反了。。另外记得加空格

2018-08-06 03:37 UTC, S1ngS1ng commented on 08-coding-interview-prep/algorithms.json
> +        "例如：<code>aab</code>应该返回 2， 因为它总共有 6 种排列方式： <code>aab</code>， <code>aab</code>， <code>aba</code>， <code>aba</code>， <code>baa</code>， <code>baa</code>，但是其中只有 2 个没有连续重复的字符（ 字符 a 是本例中的重复字符 ）：<c
全角符号之后不加空格。

2018-08-06 03:37 UTC, S1ngS1ng commented on 08-coding-interview-prep/algorithms.json
> +        "如果你遇到了困难，请点击 <a href='http://forum.freecodecamp.org/t/how-to-get-help-when-you-are-stuck/19514'target='_blank'> 帮助 </a>。你可以找人” 结对编程 “，但不要因此放弃思考。"
`你可以找人” 结对编程 “`

这里引号用的也不对

2018-08-06 03:37 UTC, S1ngS1ng commented on 08-coding-interview-prep/algorithms.json
> +        "function permAlone(str) {\n  return permutor(str).filter(function(perm) {\n    return !perm.match(/(.)\\1/g);\n  }).length;\n}\n\nfunction permutor(str) {\n  // http://staff.roguecc.edu/JMil
这个 solutions 是不需要翻译的。 @huluoyang 确认下？我记得这个只是用来执行判断的

2018-08-06 03:37 UTC, S1ngS1ng commented on 08-coding-interview-prep/algorithms.json
> +            "return str;",
这里的缩进不要移除，这个是用来在编辑器中显示代码的，去掉之后缩进就没了。

2018-08-06 03:37 UTC, S1ngS1ng commented on 08-coding-interview-prep/algorithms.json
> +            "var check = (i) => (i == arr.length - 1) ? true : (arr[i] > arr[i + 1]) ? false : check(i + 1);",
这里改了应该没事儿，但最好不要动，否则后续更新的时候会影响 diff 的判断

2018-08-06 05:57 UTC, BigFaceMaster commented on 08-coding-interview-prep/algorithms.json
> +            "return str;",
这里怕是插件的锅哦。。。

2018-08-06 05:57 UTC, BigFaceMaster commented on 08-coding-interview-prep/algorithms.json
> +            "var check = (i) => (i == arr.length - 1) ? true : (arr[i] > arr[i + 1]) ? false : check(i + 1);",
插件。。。

2018-08-06 20:58 UTC, S1ngS1ng commented
@BigFaceMaster 好 👍  把前面 comment 里提到的改下就好啦，没别的问题

2018-08-07 00:53 UTC, merged