Translation of intermediate-algorithm-scripting, 50%
FreeCodeCampChina/challenges pull request #11
Opened 2018-07-22 09:13 UTC by S1ngS1ng

算法和数据结构 - 中级算法

2018-07-25 17:22 UTC, huluoyang requested changes

2018-07-25 17:22 UTC, huluoyang commented on 02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting.json
> +        "注意，既然需要对两数之间的所有数求和，那么就先要考虑好如何获取这些数。"
追求句子的整体意思翻译，而不逐字翻译，用自己的语言来组织挺好的。
这里`那么=>那`可能会更好点。

2018-07-25 17:22 UTC, huluoyang commented on 02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting.json
> +        "<strong>注意：</strong><br>返回数组中的元素顺序不会影响测试结果。"
nice

2018-07-25 17:22 UTC, huluoyang commented on 02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting.json
> +        "如果你遇到了问题，请点击 <a href='http://forum.freecodecamp.org/t/how-to-get-help-when-you-are-stuck/19514' target='_blank'>帮助</a>。",
我会把这行翻译拎出来统一成标准

2018-07-26 05:45 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting.json
> +        "注意，既然需要对两数之间的所有数求和，那么就先要考虑好如何获取这些数。"
@huluoyang make sense 👍

2018-07-26 06:14 UTC, merged

2018-07-26 06:15 UTC, huluoyang commented
星星翻译的速度就是快，不拘泥于原文，用自己的语言来组织，nice。

2018-07-30 06:25 UTC, wudifeixue commented on 02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting.json
> +        "如果你遇到了问题，请点击 <a href='http://forum.freecodecamp.org/t/how-to-get-help-when-you-are-stuck/19514' target='_blank'>帮助</a>。",
原来如此，标准是这么来的