Translate of object-oriented-programming, 20% completed
FreeCodeCampChina/challenges pull request #12
Opened 2018-07-22 13:43 UTC by XiaoLuo01

2018-07-25 17:36 UTC, S1ngS1ng commented on .gitignore
> +
这个既然不是你的 changes，请把这个改动删掉，否则后续会很难管理。
记得使用 `git pull --rebase`，就不会有这个问题了。
如果不确定如何操作，有空了微信我

2018-07-26 08:03 UTC, S1ngS1ng requested changes
@XiaoLuo01 @huluoyang 考虑下：
我觉得，前面对实际生活的描述中，`object` 应该翻译成“物体”。毕竟`object`本身就有这个意思。
或者可以加一句：
`在英文中，object 既有“对象”又有“物体”的意思`
你们觉得？

@XiaoLuo01 主要是通顺性的问题。改的时候多读几遍吧

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "想想我们在生活中每天都可见到的事物：比如汽车、商店以及小鸟等。这些都是 <code>对象</code>：所以对象就是这些人们可以观察和与之互动的实体事物。",
`这些都是 <code>对象</code>`
这里“是”之后不需要空格，因为“对象”也是全角字符。

下同

--------

这里和下文的“对象”（包括评论中的），如果指的是实际生活中的东西，我觉得翻译成“物体”更合适。见 review comments

这里的 line comments，我就先用“对象”代替了

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "Javascript 中的 <code>对象</code> 被用来模拟现实世界中的对象，并赋予他们 <code>属性</code> 和行为，就像它们在现实世界中的对应物一样。下面是使用这些概念来创建一个 <code>duck</code> <code>对象</code> 的示例：",
`Javascript ` => `JavaScript `
注意大小写

![image](https://user-images.githubusercontent.com/13592559/43244131-7b07f392-905e-11e8-9a81-f27c50bbb6b7.png)

---------

`被用来模拟现实世界中的对象` 这句，建议改成主动句，读起来通顺些。
其实 `model` 在这里有点儿“建模”的意思。感觉说“是对现实世界中对象的抽象”，会不会~~更好~~更难理解= =

建议：`JavaScript 中的 <code>对象</code> 可以用来描述现实世界中的对象`

**特别是这句，我觉得翻译成“物体”更好**。毕竟，现实生活中说“对象”，比较奇怪（第一反应肯定是别的意思 🌝

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "这个 <code>duck</code> <code>对象</code> 有两组键值对：一个是属性 <code>name</code> 的值是 \"Aflac\" 和 一个是属性 <code>numLegs</code> 的值是2。",
但这里翻译成“对象”，我觉得没问题

-------

`一个是属性 <code>name</code> 的值是 \"Aflac\" 和 一个是属性 <code>numLegs</code> 的值是2。` =>

`一个是属性 <code>name</code>，它的值为 \"Aflac\"；另一个是属性 <code>numLegs</code>，它的值是 2。`

`2` 之前要加空格

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "创建一个 <code>dog</code> <code>对象</code>，并给这个对象添加两个属性：<code>name</code> 和 <code>numLegs</code>，同时分别给这两个属性设置一个字符串和数字。"
`分别给这两个属性设置一个字符串和数字。` =>
`把这两个属性的值分别设为字符串和数字。`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +          "text": "<code>dog</code> 应该就是一个 <code>object</code>。",
`应该就是` => `应该是`

下一行也要改

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +          "text": "<code>dog</code> 应该有一个 <code>name</code> 属性被设置了一个 <code>string</code>。",
`<code>dog</code> 应该有一个 <code>name</code> 属性被设置了一个 <code>string</code>。` 建议 =>
`<code>dog</code> 应该有一个 <code>name</code> 属性，且它的值是一个字符串。`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +          "testString": "assert(typeof(dog.numLegs) === 'number', '<code>dog</code> 应该有一个 <code>numLegs</code> 属性被设置了一个 <code>number</code>。');"
这几行同理，记得一起改，保证一致

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "在上一个挑战中创建了一个拥有不同的 <code>属性</code> 的 <code>对象</code>，接下来你就了解到是如何访问这些 <code>属性</code> 的，请看下面的例子：",
`在上一个挑战中创建了一个拥有不同……` 建议 =>
`在上一个挑战中，我们创建了一个拥有不同……`
或
`我们在上一个挑战中创建了一个拥有不同……`

--------

`接下来你就了解到是如何访问这些 <code>属性</code> 的，请看下面的例子：` =>
`现在我们来看看该如何访问这些<code>属性</code>：`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "<blockquote>let duck = {<br>&nbsp;&nbsp;name: \"Aflac\",<br>&nbsp;&nbsp;numLegs: 2<br>};<br>console.log(duck.name);<br>// 这里将会输出 \"Aflac\" 到控制台 </blockquote>",
`这里将会输出 \"Aflac\" 到控制台` =>
`这段代码会在控制台中输出 \"Aflac\"`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "点标记可以用在一个 <code>对象</code> 名称后面：如<code>duck</code>，点后面就是 <code>属性</code> 的名称用来接收一个 \"Aflac\" 值：如 <code>name</code>。",
`点标记` =>
`点号表示法`

参考：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Property_Accessors

整句建议：
`我们可以用“点号表示法”来访问对象的属性，只需要在<code>对象</code>名称后面加上 <code>.</code> 以及<code>属性</code>名即可。比如，<code>duck.name</code> 就可以访问到 \"Aflac\"。`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "请在你的控制台里面输出 <code>dog</code> 这个对象的两个 <code>属性</code>。"
删掉“你的”

`请在控制台里输出 <code>dog</code> 对象中两个<code>属性</code>对应的值。`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +            "// 在下一行添加你的代码",
参考：

https://github.com/FreeCodeCampChina/freecodecamp.cn/blob/dev/seed/challenges/01-front-end-development-certification/basic-javascript.json#L3342

下同

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "<code>方法</code> 其实就是一个函数 <code>属性</code>。它可以为一个 <code>对象</code> 添加不同的行为属性。以下就是一个带有方法属性的 <code>duck</code> 示例：",
`<code>方法</code> 其实就是一个函数 <code>属性</code>` =>

`<code>方法</code>其实是一个值为函数的<code>属性</code>`

-------

`。它可以为一个 <code>对象</code> 添加不同的行为属性` =>

`，它可以为一个<code>对象</code>添加不同的行为。`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "这个例子给 <code>duck</code> 对象添加了一个 <code>sayName</code> <code>method</code>，这个方法返回一个 <code>duck</code> 名字的语句",
`<code>method</code>` 要翻译成 `<code>方法</code>`

------

`这个方法返回一个 <code>duck</code> 名字的语句` =>
`这个方法返回一个包含 <code>duck</code> 名字的句子。`

注意结尾句号

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "注意：这个 <code>method</code> 在返回语句的声明里面使用了 <code>duck.name</code> 方式来接收 code>name</code> 的属性值。在下一个挑战中我们将会使用另外一种方法来实现。",
`<code>method</code>` 要翻译成 `<code>方法</code>`

----------

`这个 <code>method</code> 在返回语句的声明里面使用了 <code>duck.name</code> 方式来接收 code>name</code> 的属性值。` =>

`这个<code>方法</code>在返回语句中使用 <code>duck.name</code> 的方式来获取 <code>name</code> 的属性值。`

code 标签漏了个 `<`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "给 <code>dog</code> <code>对象</code> 设置一个名为 <code>sayLegs</code> 的方法，方法里面返回一个 \"This dog has 4 legs.\" 的语句。"
`方法里面返回一个 \"This dog has 4 legs.\" 的语句。` =>
`并让它返回 \"This dog has 4 legs.\" 这句话。`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +          "testString": "assert(typeof(dog.sayLegs) === 'function', '<code>dog.sayLegs()</code>应该是一个方法。');"
`应该是一个 <code>function</code>` 或者 `应该是一个函数`，会不会好些？

之前说了，`function` 优先翻译成“函数”，`method` 优先翻译成“方法”

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +          "text": "<code>dog.sayLegs()</code> 应该返回给定的字符串 - 需要注意标点和间距的问题。",
注意标点，`-` 和 `—` 是不同的。后者才是中文的破折号。
或者这里用逗号也没问题。下同

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "在上一个挑战中介绍了如何给 <code>duck</code> 对象设置一个 <code>方法</code> 属性。",
`在上一个挑战中介绍了如何给 <code>duck</code> 对象设置一个 <code>方法</code> 属性。` =>

`在上一个挑战中我们了解了该如何给 <code>duck</code> 对象设置一个<code>方法</code>属性。`

---------

` It used <code>duck.name</code> dot notation to access the value for the <code>name</code> property within the return statement:` 这句话貌似忘翻译了

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "<code>this</code> 是一个很深入的话题，而上面那个例子也只是使用 <code>this</code> 的一种方法而已。在当面的上下文环境中，<code>this</code> 指向的就是与这个方法有关联的 <code>duck</code> 对象。",
`很深入的话题` => `很复杂的知识点`

-------

`当面` => `当前`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "修改 <code>dog.sayLegs</code> 方法以将所有直接对 <code>dog</code> 的引用删除。可以使用 <code>duck</code> 示例进行指导。"
`可以使用 <code>duck</code> 示例进行指导。` => 
`可以参考上面的例子。`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "这个 <code>构造函数</code> 定义了一个 <code>Bird</code> 对象，其属性 <code>name</code>、 <code>color</code> 和 <code>numLegs</code> 的值分别被设置为 ‘Albert’、‘blue’ 和 2。",
`<code>name</code>、 <code>color</code>` 删掉顿号之后的空格

-----

` ‘Albert’、‘blue’ 和 2。` 建议 => 
`<code>Albert</code>、<code>blue</code> 和 2。`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "<ul><li><code>构造函数</code> 必须要以大写字母开头来定义，用来区别 <code>构造函数</code> 和其他非构造函数。</li><li><code>构造函数</code> 使用 <code>this</code> 关键字来给它将创建的这个对象设置新的属性。在 <code>构造函数</code> 里面，<code>this</code> 指向的就是它新创
`<code>构造函数</code> 必须要以大写字母开头来定义，用来区别 <code>构造函数</code> 和其他非构造函数。` =>
`<code>构造函数</code>函数名的首字母最好大写，这是为了方便我们区分<code>构造函数</code>和其他非构造函数。`

-----

`需要通过返回值。` => `需要设置返回值。`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "创建一个 <code>构造函数</code>：<code>Dog</code>。给其添加 <code>name</code>, <code>color</code> 和 <code>numLegs</code> 属性并分别给它们设置为：字符串，字符串和数字。"
这里的英文逗号改一下

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +          "text": "<code>Dog</code> 应该有一个 <code>name</code> 属性被设置为一个字符串。",
`<code>Dog</code> 应该有一个 <code>name</code> 属性被设置为一个字符串。` => 

`<code>Dog</code> 应该有一个 <code>name</code> 属性且它的值是一个字符串。`

下同

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "以下是在前一个挑战中学习到并创建的一个 <code>Bird</code> 构造函数：",
参考上面的建议

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "注意：通过构造函数创建对象的时候要使用 <code>new</code> 操作符。因为只有这样， Javascript 才知道要给 <code>Bird</code> 这个构造函数创建一个新的 <code>实例</code> 名字叫做 <code>blueBird</code>。如果不使用 <code>new</code> 操作符来新建对象，那么构造函数里面的 <code>th
`因为只有这样， Javascript ` 多余的空格，以及 JavaScript 的拼写有误

-------

`创建一个新的 <code>实例</code> 名字叫做 <code>blueBird</code>` =>
`创建一个新的 <code>实例</code>：<code>blueBird</code>`
或
`创建一个叫做 <code>blueBird</code> 的新 <code>实例</code>`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "使用上一个课时中的 <code>Dog</code> 构造函数创建一个 <code>Dog</code> 的新实例，分配给其一个变量名 <code>hound</code>。"
`分配给其一个变量名 <code>hound</code>` =>

`并把它赋值给变量 <code>hound</code>`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "上一个挑战中 <code>Bird</code> 和 <code>Dog</code> 构造函数运行得不错。但是，注意到没有：所有通过 <code>Bird</code> 构造函数创建出来的实例 <code>Birds</code> 都自动的取名为 ‘Albert’、颜色为蓝色、都是两条腿。如果你想要新创建出来的小鸟们拥有不同的名字和颜色要怎么办呢？当然，手动的去修改每一个小鸟
`‘Albert’` => `Albert`
感觉可以不加

--------

`都自动的取名为 ‘Albert’、颜色为蓝色、都是两条腿。` =>
`都自动的取名为 Albert，颜色都是蓝色，还都有两条腿。`

-------

`很多没必要的工作量：` => `很多无谓的工作量：`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "假如你写了一个程序来追踪一个鸟舍里面的几百只甚至几千只不同的小鸟。这样将会花费很多很多的时间去创建所有的小鸟实例并给它们的属性一一修改为不同的值。",
`。这样将会花费很多很多的时间去创建……` =>
`，你将会话费很多时间去创建……`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "为了减轻创建不同的 <code>Bird</code> 对象，你可以给你的 <code>Bird</code> 设置为可以接收参数的构造函数：",
减轻……的工作量

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "然后将值通过形参的方式传递给 <code>Bird</code> 构造函数来定义每一个唯一的小鸟实例：",
`形参` => `参数`（而且，这里其实是实参）

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "这给 <code>Bird</code> 的名字和颜色属性分别赋值为 ‘Bruce’ 和红色提供了另外一种方法。但 <code>numLegs</code> 属性被默认赋值为 2。",
同上，去掉单引号

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "这样一来构造函数就变得很灵活了。现在可以直接定义每个 <code>Bird</code> 实例在创建时的属性，这是 JavaScript 构造函数非常有用的一种方式。它们根据共同或相似的属性和行为将对象归纳为一组，并能够自动的创建各自实例。",
`非常有用的一种方式` => `非常实用的用法之一`？
想不到怎么表述= =！ @huluoyang 　

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "创建另一个 <code>Dog</code> 构造函数。这一次，给它设置两个参数： <code>name</code> 和 <code>color</code>，同时设置 <code>numLegs</code> 的值默认为 4。然后创建一个新 <code>Dog</code> 实例保存为变量名： <code>terrier</code>，再将两个字符串通过参数的形式传入 <c
建议还是用“给……赋值”这种说法

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +          "text": "<code>Dog</code> 应该有一个 <code>numLegs</code> 属性被赋值为 4。",
`且值为 4`

参考上面的 comment。下同

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "不管何时通过构造函数创建新的新对象都是这个构造函数的一个 <code>实例</code>。 JavaScript 提供了一种很简便的方法来验证这个事实，那就是通过 <code>instanceof</code> 操作符。<code>instanceof</code> 允许你将对象与构造函数之间进行比较，根据对象是否由这个构造函数创建的返回相应的 <code>true</code
`……<code>实例</code>。 JavaScript 提供了……` 句号之后多了个空格

------

`不管何时通过构造函数创建新的新对象都是这个构造函数的一个 <code>实例</code>。` =>
`凡是通过构造函数创建出的新对象，都叫做这个构造函数的<code>实例</code>。`

-------

删掉 `相应的`

------

`以下就是一个示例：` 删掉“就”

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "给 <code>House</code> 构造函数创建一个新实例，取名为 <code>myHouse</code> 并且传递一个数字给 <code>bedrooms<code> 参数。然后使用 <code>instanceof</code> 操作符证明这个对象是否是 <code>House</code> 的实例。"
`证明` => `验证`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +          "text": "一定要使用 <code>instanceof</code> 操作符证明 <code>myHouse</code> 这个对象是 <code>House</code> 构造函数的一个实例。",
`一定要` => `请务必`

下同

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "请看下面的举例，<code>Bird</code> 构造函数定义了两个属性：<code>name</code> 和 <code>numLegs</code>：",
`举例` => `实例` 或 `例子`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "<code>name</code> 和 <code>numLegs</code> 被叫做 <code>自身</code> 属性，因为他们是直接在实例对象上定义的。这就意味着 <code>duck</code> 和 <code>canary</code> 这两个对象都有属于自己的这些属性的单独副本。",
`这就意味着 <code>duck</code> 和 <code>canary</code> 这两个对象都有属于自己的这些属性的单独副本。` =>
`这就意味着 <code>duck</code> 和 <code>canary</code> 这两个对象分别拥有这些属性的独立副本。`

会不会好些？因为 `own` 是修饰 `copy` 的，而不是修饰 `properties`

下同

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "将 <code>canary</code> 对象里面的 <code>自身</code> 属性添加到 <code>canary</code> 数组里面。"
`添加到 <code>canary</code> 数组里面。` =>
`添加到 <code>ownProps</code> 数组里面。` 吧？

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +          "text": "<code>ownProps</code> 应该包含了 <code>\"numLegs\"</code> 和 <code>\"name\"</code> 两个属性的值。",
`应该包含了` => `应该包含`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +          "text": "在不使用内置方法 <code>Object.keys()</code> 的情况下解决这个挑战。",
`解决这个挑战` => `完成这个挑战`

一般说“解决问题”，不说“解决挑战”吧

下同

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "由于 <code>numLegs</code> 属性可能对 <code>Bird</code> 的所有实例都具有相同的值，所以在每一个 <code>Bird</code> 的实例中本质上都有一个重复的变量 <code>numLegs</code>。",
`由于 <code>numLegs</code> 属性可能对 <code>Bird</code> 的所有实例都具有相同的值` => 
`所有 <code>Bird</code> 实例可能会有相同的 <code>numLegs</code> 值`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "这里有一个更好的方法可以解决上述问题，那就是使用 <code>Bird’s</code> <code>原型</code>。<code>原型</code> 是一个可以在所有 <code>Bird</code> 实例之间共享的对象。以下是一个如何在 <code>Bird prototype</code> 中添加 <code>numLegs</code> 属性的：",
`那就是使用 <code>Bird’s</code> <code>原型</code>` => `那就是使用 <code>Bird</code> 的<code>原型</code>`

这个是所有格。

-----

`以下是一个在 <code>Bird prototype</code> 中添加 <code>numLegs</code> 属性的示例：`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "现在所有的 <code>Bird</code> 实例都拥有了共同的 <code>numLegs</code> 属性。",
`属性` => `属性值`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "由于所有的实例都可以在 <code>原型</code> 上自动的拥有属性，所以可以把 <code>原型</code> 看作是创建对象的 \"recipe\"。",
`由于所有的实例都可以在 <code>原型</code> 上自动的拥有属性` =>
`由于所有的实例都可以继承 <code>原型</code> 上属性`

------

`看作是创建对象的 \"recipe\"。` => `看作是创作对象的\"配方\"。`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "请注意： <code>duck</code> 和 <code>canary</code> 的 <code>原型</code> 是<code>Bird</code> 构造函数原型 <code>Bird.prototype</code> 的一部分。JavaScript 中几乎所有的对象都有一个 <code>原型</code> 属性，它是创建它的构造函数的一部分。",
删掉冒号之后多余的空格

------

`它是创建它的构造函数的一部分。` 读起来有点儿不顺，但想不出怎么改= = @huluoyang

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "现在你已经了解了两种属性: <code>自身</code> 属性和 <code>原型</code> 属性。 <code>自身</code> 属性是直接在对象实例它自己内部定义的。而 <code>原型</code> 属性是定义在 <code>prototype</code> 上的：",
去掉句号后多余的空格

--------

`<code>自身</code> 属性是直接在对象实例它自己内部定义的。` =>
`<code>自身</code> 属性是直接在对象上定义的。`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "这是一个告诉你如何将 <code>duck’s</code> <code>自身</code> 属性和 <code>原型</code> 属性分别添加到 <code>ownProps</code> 数组和 <code>prototypeProps</code> 数组里面：",
`这是一个告诉你如何将 <code>duck’s</code> <code>自身</code> 属性和 <code>原型</code> 属性……` => 

`这个示例会告诉你如何将 <code>duck</code> 的<code>自身</code>属性和<code>原型</code>属性……`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +          "testString": "assert(!/\\Object.keys/.test(code), '在不使用内置方法 <code>Object.keys()</code> 的情况下解决这个挑战。');"
`完成`。参考上面的 comment

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "在上一个挑战中创建的实例对象 <code>duck</code> 和 <code>beagle</code> 都有一个特殊的  <code>constructor</code> 属性：",
多余的空格

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "<code>constructor</code> 属性的一个优势就是通过检查这个属性来找出它是一个什么样的对象。下面是一个例子，来看看是怎么使用的：",
`<code>constructor</code> 属性的一个优势就是通过检查这个属性来找出它是一个什么样的对象。` => 
`<code>constructor</code> 属性存在的一个优势是，我们可以通过检查这个属性来找出它是一个什么样的对象。`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "<strong>注意：</strong><br>由于 <code>constructor</code> 属性可以被重写（在下面两节挑战中将会遇到） 所以通常使用 <code>instanceof</code> 方法来检查对象的类型要更好。",
去掉） 后多余的空格

-------

`由于 <code>constructor</code> 属性可以被重写（在下面两节挑战中将会遇到），所以使用 <code>instanceof</code> 方法来检查对象的类型会更好。`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "写一个 <code>joinDogFraternity</code> 函数，传入一个 <code>candidate</code> 参数并使用 <code>constructor</code> 属性来判断传入的 candidate 是不是 <code>Dog</code> 创建的对象实例，如果是返回 <code>true</code> 否则返回 <code>false</cod
`如果是返回 <code>true</code> 否则返回 <code>false</code>。` =>
`如果是，就返回 <code>true</code>，否则返回 <code>false</code>。`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +          "text": "<code>joinDogFraternity</code> 应该要使用 <code>constructor</code> 属性。",
`<code>joinDogFraternity</code> 应该要使用` => 
`<code>joinDogFraternity</code> 中应该用到`？

下同

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "这将在添加许多属性的时候变得单调乏味的。",
`变得单调乏味的` => `变得单调乏味`

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "一种更有效的方法就是给对象的 <code>prototype</code> 设置为一个已经包含了属性的新对象。这样一来，所有属性都可以一次性被添加进来：",
删掉“被”

2018-07-26 08:03 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/object-oriented-programming.json
> +        "通过给 <code>prototype</code> 设置为新对象的方法，给 <code>Dog</code> 构造函数的 <code>原型</code> 上添加一个属性 <code>numLegs</code> 和两个方法 <code>eat()</code> 、<code>describe()</code>。"
`在……上`

------

`和两个方法 <code>eat()</code> 、<code>describe()</code>。` =>
`以及两个方法：<code>eat()</code> 和 <code>describe()</code>。`

2018-07-27 17:43 UTC, S1ngS1ng approved these changes
Thanks 👍

2018-07-28 08:56 UTC, huluoyang commented
🎉 恭喜小罗的第一个PR成功进入仓库，keep moving!

2018-07-28 08:56 UTC, merged