01-responsive-web-design/css-flexbox.json 翻译完成
FreeCodeCampChina/challenges pull request #13
Opened 2018-07-23 03:03 UTC by ssshooter

01-responsive-web-design/css-flexbox.json 翻译完成

2018-07-27 22:09 UTC, S1ngS1ng requested changes
1. 每道题都加了 `translations: {}`，应该去掉吧？
2. 根据昨天的讨论，`<code></code>` 外面不加空格。麻烦你更新下，谢谢
3. 我觉得 option 其实可以不必翻译成“选项”，有时和翻译成“值”，或者“可用值”（放到句子里就是 “xxx 属性还有 yyy、zzz 这些值可以使用”）。你觉得呢？
4. “项目”（flex items），要不要按照 MDN 上的翻译？
5. 记得更新下 md 文件，有冲突。`pull --rebase` 一下

主要是通顺性的问题，整体翻译的很不错 👍 


（Align Elements Using the justify-content Property 这道题的翻译质量很高）

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "这节会使用另一个挑战方法为你介绍 CSS 弹性盒子。挑战会先解释理论，然后动手做一个弹性盒子布局的简单的推文组件。" ,
意思基本正确。建议：

`在这一节，我们会用一种不同的挑战方式来学习一下如何更灵活地使用 CSS 布局。首先，我们会先用一个挑战解释原理，然后使用“弹性盒子”（flexbox）调整一个推文组件的样式来完成挑战。`

注意第一句话其实没有提到 flexbox

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "给一个元素赋予 CSS 属性 <code>display: flex;</code>，你就可以使用其他 flex 属性构建响应式页面了。",
`只要在一个元素的 CSS 中添加<code>display: flex;</code>，那就可以使用其他 flex 属性来构建响应式页面了。`

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "为 <code>#box-container</code> 添加 <code>display</code> 属性，设置为 flex。"
`添加 <code>display</code> 属性，设置为 flex。` =>
`添加 <code>display</code> 属性，设置它的值为 flex。`

或

`添加 <code>display</code> 属性且设置值为 flex。`

我比较建议第一种

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "我们以右边的内嵌推文为基础开始实践。一些元素换一个布局方式或许更好看。上一个挑战演示了 <code>display: flex</code>，现在你需要把它添加到内嵌推文的多个组件来调整它们的位置。",
`内嵌推文的多个组件` => `推文内嵌的多个组件中`

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "为下列项目添加 CSS 属性 <code>display: flex</code> —— 注意，选择器已在 CSS 中准备好：",
这里的破折号有待讨论

--------

`选择器已在 CSS 中准备好：` => `选择器已在 CSS 中给出：`

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "添加了 <code>display: flex</code> 的元素会成为 flex 容器。只要把 <code>flex-direction</code> 属性添加到父元素，并设置其为 row 或 column，便可以轻易横或竖排列它的子元素。设为 row 可以让子元素水平排列，column 可以让子元素垂直排列。",
`，便可以轻易横或竖排列它的子元素。` => ` 就可以改变其子元素的排列方式。`

不需要逗号了

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +      "translations": {},
这个应该去掉吧？下同

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "添加 CSS 属性 <code>flex-direction</code> 到 <code>#box-container</code> 元素，赋值为 column。"
给……添加 xxx 属性

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "回忆一下，把 flex 容器设为一个行，它的子元素会从左到右逐个排列，把 flex 容器设为一个列，它的子元素会从上到下垂直叠在一起。子元素排列的方向被称为 <strong>main axis（主轴）</strong>。对于行，主轴水平贯穿每一个项目；对于列，主轴垂直贯穿每一个项目。",
`把 flex 容器设为一个行，它的子元素会从左到右逐个排列，把 flex 容器设为一个列，它的子元素会从上到下垂直叠在一起。` =>

`把 flex 容器设为一个行，它的子元素会从左到右逐个排列；把 flex 容器设为一个列，它的子元素会从上到下逐个排列。`

-----

`项目` 建议 => `子元素`

会不会好些？

https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox

MDN 上，flex items 叫 flex 元素；flex container 叫 flex 容器

@huluoyang 加到 wiki 吧？

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "之前两项挑战把 <code>flex-direction</code> 设为 row。这个属性还能创建一个列，让子元素垂直层叠在 flex 容器中。",
`层叠` => `排列`

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "<ul><li><code>flex-start</code>：从 flex 容器的前端开始排列项目。对行来说是把项目都靠左放，对于列是把项目都靠顶部放。</li><li><code>flex-end</code>：从 flex 容器的后端开始排列项目。对行来说是把项目都靠右放，对于列是把项目都靠底部放。</li><li><code>space-between</code>：项
`空位` => `间距`

-------

同样，`项目` 建议 => `子元素`。。或参考 MDN

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "<strong>Bonus</strong><br>在编辑器里试试 <code>justify-content</code> 的其他选项，看看它们之间的区别。但要通过挑战必须把值设为 center 哦。"
`<strong>Bonus</strong><br>在编辑器里试试 <code>justify-content</code> 的其他选项，看看它们之间的区别。但要通过挑战必须把值设为 center 哦。` => 
`<strong>提示：</strong><br>你可以在编辑器里试试<code>justify-content</code>的其他值，看看它们之间的区别。但要通过挑战，你必须把值设为 center。`

注意同步修改后文出现的

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "上一项挑战展示了 <code>justify-content</code> 属性的作用。对于内嵌推文，可以应用在 <code>.profile-name</code>，以对齐它的子元素。",
`对于内嵌推文，可以应用在 <code>.profile-name</code>，以对齐它的子元素。` => 
`如果我们想对齐推文内的子元素，就可以把<code>justify-content</code>应用在<code>.profile-name</code>上。`

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +          "text": "<code>.profile-name</code> 元素的 <code>justify-content</code> 属性可选以下值:center、flex-start、flex-end、space-between、space-around。",
这里翻译的没错，只是应该用全角冒号。下同

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "Flex 容器中，与主轴垂直的，被称为 <strong>cross axis（交叉轴）</strong>。行的交叉轴是垂直的，列的交叉轴是水平的。",
去掉`被称为`前面的逗号吧

也可以说：`Flex 容器中，与主轴垂直的叫做 <strong>cross axis（交叉轴）</strong>。`
通顺一些

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "<ul><li><code>flex-start</code>：从 flex 容器的前端开始排列项目。对行来说是把项目都靠顶部放，对于列是把项目都靠左放。</li><li><code>flex-end</code>：从 flex 容器的后端开始排列项目。对行来说是把项目都靠底部放，对于列是把项目都靠右放。</li><li><code>center</code>：把项目的位置调整
`基线对其地排列。` 应该是“对齐”吧？

-------

`可以认为字体坐落在基线上。` 其实这个是其他语言（比如英文）中才有的概念，对中文并不适用。翻译的时候有必要提一句。

参考：https://en.wikipedia.org/wiki/Baseline_(typography)
以及：https://www.zhihu.com/question/22183501

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "CSS flexbox 有一个把 flex 项目拆分为多行（或列）的特性。默认情况下，flex 容器会调整项目大小，把它们都塞到一起。如果是行的话，所有项目都会在一条直线上。",
`拆分为多行（或列）` 感觉中文表达应该是：
`拆分为多行（或多列）` 或者 `拆分为多行／列`。推荐第一种

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "为 <code>#box-1</code> 和 <code>#box-2</code> 添加 CSS 属性 <code>flex-shrink</code>，<code>#box-1</code> 的值设为 1， and <code>#box-2</code> 的值设为 2。"
这里的 and 没翻译。翻译后记得去掉 and 前面的空格

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "与 <code>flex-shrink</code> 相对的是 <code>flex-grow</code>。回忆 <code>flex-shrink</code> 在容器太小时作控制，<code>flex-grow</code> 属性是在容器太大时作控制.",
`回忆 <code>flex-shrink</code> 在容器太小时作控制，<code>flex-grow</code> 属性是在容器太大时作控制.` =>
`你应该还记得，<code>flex-shrink</code>会在容器太小时对元素作出调整。相应地，<code>flex-grow</code>会在容器太大时对元素作出调整。`

注意，结尾用全角句号

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "上面几个 flex 属性有一个缩写法。<code>flex-grow</code>、<code>flex-shrink</code> 和 <code>flex-basis</code> 属性可以在 <code>flex</code> 中一同设置。",
`缩写法` => `简写方式`？
参考：https://developer.mozilla.org/zh-CN/docs/Web/CSS/flex

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "在 <code>#box-1</code> and <code>#box-2</code> 添加 <code>flex</code> 属性。把 <code>#box-1</code> 设置成 <code>flex-grow</code> 为 2，<code>flex-shrink</code> 为 2, <code>flex-basis</code> 为 150px。把 <co
有一个逗号是半角的

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "上面设置的属性,在容器大于 300px 时，会让 <code>#box-1</code> 填充倍率为 <code>#box-2</code> 的两倍；在容器小于 300px 时，缩小倍率为 <code>#box-2</code> 的两倍。300px 是两个盒子的 <code>flex-basis</code> 的值之和。"
同样，第一个逗号是半角的

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "<code>order</code> 属性告诉 CSS flex 容器里项目的顺序。 默认情况下，项目排列顺序与源 HTML 文件中顺序相同。这个属性接受数字作为参数，负数可用。",
句号之后多了个空格

------

`负数可用` => `可以使用负数`

2018-07-27 22:09 UTC, S1ngS1ng commented on 01-responsive-web-design/css-flexbox.json
> +        "<code>align-self</code> 的可能值与 <code>align-items</code> 一样，并且它会覆盖 <code>align-items</code> 的值。",
`可能值` => `允许值`，如何？

2018-07-28 02:02 UTC, ssshooter commented on 01-responsive-web-design/css-flexbox.json
> +        "<ul><li><code>flex-start</code>：从 flex 容器的前端开始排列项目。对行来说是把项目都靠顶部放，对于列是把项目都靠左放。</li><li><code>flex-end</code>：从 flex 容器的后端开始排列项目。对行来说是把项目都靠底部放，对于列是把项目都靠右放。</li><li><code>center</code>：把项目的位置调整
是需要在文中添加提示吗？

2018-07-28 03:22 UTC, SSShooter commented
@S1ngS1ng 感谢细心校对，已作修改

2018-07-29 16:48 UTC, S1ngS1ng approved these changes

2018-07-29 16:54 UTC, S1ngS1ng commented
@ssshooter 处理一下 conflicts 就好。现在你的 PR 里包含了不属于你的改动。如果不好处理，你可以新开一个 branch，然后 apply 你在这个 branch 的改动就好。

```bash
# 获取 upstream 的 HEAD
git fetch upstream
# 根据最新的 upstream/translate branch 新建 translate-css-flexbox branch
git checkout -b translate-css-flexbox upstream/translate

# apply 这个 PR 对应的本地 branch 的文件
git checkout translate-/01-responsive-web-design/css-flexbox.json -- 01-responsive-web-design/css-flexbox.json
git checkout translate-/01-responsive-web-design/css-flexbox.json -- 01-responsive-web-design/css-flexbox.md

# 提交
git add .
git commit -m "xxxx"
git push origin translate-css-flexbox
```

2018-07-30 01:26 UTC, SSShooter commented
@S1ngS1ng 这样是不是要重新提 pr 呢？

2018-07-30 06:12 UTC, S1ngS1ng commented
@ssshooter 不需要的。你可以 `pull --rebase` 然后本地处理，然后 push 就行。
但 `managing-packages-with-npm.json` 这个 json 和 md，你是不该改的吧？这种情况下，新建个 branch 重新提交方便些。你的 commit history 里有 merge commit。所以 `pull --rebase` 会不太好处理

2018-07-30 13:28 UTC, SSShooter commented
@S1ngS1ng 😂 对不起有点问题...新分支是建了，文件也提交了，但是我发现 PR 只可以修改目标分支不能修改来源分支呀...
![image](https://user-images.githubusercontent.com/13051472/43400128-69d308d4-943f-11e8-8bbb-6926de6c4c68.png)

2018-07-30 18:01 UTC, S1ngS1ng commented
@ssshooter 没关系的，用新的 branch 再开个 PR 就好啦。回头这个 PR 关掉就行

2018-07-30 19:23 UTC, merged

2018-07-30 19:23 UTC, huluoyang commented
@ssshooter  🎉 恭喜你这个 PR 已经 merge 进仓库了，你完成了你的光荣使命。