Add CONTRIBUTING.md
FreeCodeCampChina/challenges pull request #15
Opened 2018-07-23 06:42 UTC by S1ngS1ng

- Add guide of git

## TODO
- Style guide

2018-07-23 19:18 UTC, huluoyang requested changes

2018-07-23 19:18 UTC, huluoyang commented on CONTRIBUTING.md
> +- conflicts：合并冲突
conflicts 虽然是合并产生的冲突，但这里翻译成冲突要好些。

2018-07-23 19:18 UTC, huluoyang commented on CONTRIBUTING.md
> +1. 首先，fork 一下 [challenges](https://github.com/FreeCodeCampChina/challenges/pulls) repo
仓库地址应该是：https://github.com/FreeCodeCampChina/challenges.git

2018-07-23 19:18 UTC, huluoyang commented on CONTRIBUTING.md
> +git checkout -b your_branch_name
`git branch your_branch_name`   新建分支
`git checkout you_branch_name` 切换分支
建议分两步，不要用简写的方式。

2018-07-23 19:18 UTC, huluoyang commented on CONTRIBUTING.md
> +# 或者你也可以打开你喜欢的编辑器（需要配置），在里面编写 commit message
建议这部分去掉，实际上在编辑器里写 commit 的情形很少，commit 信息尽量一行写完。

2018-07-23 19:18 UTC, huluoyang commented on CONTRIBUTING.md
> +1. 关联上游 repo 至本地项目。注意，`upstream` 只是一个本地的 reference，你可以根据自己的习惯命名：
注意部分可去掉。如无必要，勿增实体。

2018-07-23 19:18 UTC, huluoyang commented on CONTRIBUTING.md
> +2. 获取上游更新，并应用到本地。以下提供三种方式：
按照 Python 的哲学，应该只向开发者提供一种最佳方式，其他方式可以自行摸索。
```bash
git pull upstream translate
git rebase
```

2018-07-23 19:18 UTC, huluoyang commented on CONTRIBUTING.md
> +    git fetch upstream
`git fetch` 只获取，并不 merge，所以此处不合适。

2018-07-23 19:18 UTC, huluoyang commented on CONTRIBUTING.md
> +    git pull --rebase upstream translate
一条命令包含太多信息，对新手不友好，高手可以这样操作。

2018-07-23 19:18 UTC, huluoyang commented on CONTRIBUTING.md
> +1. `pull` 或 `rebase` 之后，如果有 conflicts，可以先使用 `git status` 查看存在 conflicts 的文件。修改成需要的版本后：
此处可全部替换成：
`git pull upstream translate` 命令执行后，命令行会出现一个 vim 的编辑器界面。
在此界面中，输入`:wq`，表示保存 merge 信息。

2018-07-23 19:18 UTC, huluoyang commented on CONTRIBUTING.md
> +3. 如果出现错误提示（多出现于 `rebase` 和 `pull` 命令），请先使用 `git status` 命令检查本地是否有未解决完成的 conflicts
任何时候出现错误，不要慌，请先使用 `git status` 命令检查当前所在的分支、当前目录是否纯净、本地是否有未解决完成的 conflicts。

2018-07-23 19:18 UTC, huluoyang commented on CONTRIBUTING.md
> +1. 建议使用 [git workflow](https://guides.github.com/introduction/flow/) 来进行分支的管理。这样我们可以提交 PR 之后继续在新的 branch 上进行后续的翻译。若需要更新当前的 PR，任何时候我们都可以切换回来
任何时候我们都可以切换回来 => 我们随时可以切换回来

2018-07-23 21:25 UTC, S1ngS1ng commented on CONTRIBUTING.md
> +1. 首先，fork 一下 [challenges](https://github.com/FreeCodeCampChina/challenges/pulls) repo
@huluoyang 好。这个我回家改

2018-07-23 21:38 UTC, S1ngS1ng commented on CONTRIBUTING.md
> +git checkout -b your_branch_name
@huluoyang 所以先 `git branch` 然后再 `checkout` 会有什么潜在的风险？因为如果在 `git branch` 那一步出了问题，哪怕是简写也不会有任何 side effect，本地不会有任何变化。

而且，习惯上，在新建 branch 之后就会切换过去。一个合理的猜想是在新建 branch 之后会设置它的 tracking branch（尽管一般这个步骤都是发生在切换之后），然而这个也可以通过
```bash
git checkout -b your_branch_name some_remote/some_branch
```
来实现。因此，我看不到分两步的必要。
在新建 branch 之后，你除了切换过去，还做过什么操作？我能想到的就是设置 tracking。

至于该不该用简写，比如，我们都习惯了 `git pull`，然而它本身就是 `git fetch` + `git merge`。为何我们不分开呢？

2018-07-23 21:57 UTC, S1ngS1ng commented on CONTRIBUTING.md
> +# 或者你也可以打开你喜欢的编辑器（需要配置），在里面编写 commit message
@huluoyang 之所以放在这里，一方面是告知大家如果这么做会发生什么，另一方面，我一直都是在 vim 里写 commit message 的。

至于原因，首先，你说的一行写完，个人觉得指的应该是 “message header”（推荐是 50 字以内），但这与 commit message 里有 messsage body 并不冲突。message header 与 message body 通过第一个空行区分。所以我会选择在 vim 里输入。

参考：https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project 中 Commit Guidelines 部分

其次，多行的 commit message 不是必须的，但我们在需要的时候可以采用，特别是 squash and merge 的时候。

以及，它丝毫不会影响 commit history 在 github 页面或命令行的外观：
![image](https://user-images.githubusercontent.com/13592559/43104941-f3c28c08-8e87-11e8-9252-1a07e1a3a402.png)
截图来自 freeCodeCamp/freeCodeCamp。注意到有个 commit 有三个点。点开之后：
![image](https://user-images.githubusercontent.com/13592559/43104978-181244ae-8e88-11e8-83f5-bebf738c0059.png)
这才是 message body

命令行里也很好办。`git log` 会输出 header 及 body，但 `git log --oneline` 就不会了。我设置了一个 alias，对应的是 `git log --oneline --decorate --graph`，看起来会很直观

2018-07-23 21:58 UTC, S1ngS1ng commented on CONTRIBUTING.md
> +1. 关联上游 repo 至本地项目。注意，`upstream` 只是一个本地的 reference，你可以根据自己的习惯命名：
@huluoyang 好的。这个可以改，因为按照这个顺序下来，用户本地应该只有 `origin`

2018-07-23 21:58 UTC, S1ngS1ng commented on CONTRIBUTING.md
> +2. 获取上游更新，并应用到本地。以下提供三种方式：
好。那就 `pull --rebase`？

2018-07-23 21:59 UTC, S1ngS1ng commented on CONTRIBUTING.md
> +    git fetch upstream
@huluoyang 下一行就是 rebase 了

2018-07-23 22:01 UTC, S1ngS1ng commented on CONTRIBUTING.md
> +    git pull --rebase upstream translate
@huluoyang 我倒不觉的这是个问题。复制粘贴，设置命令行 alias 总是可以的，不需要每次都手打啊。以及之比 `git pull upstream translate` 多了个 `--rebase`。。

2018-07-23 22:17 UTC, S1ngS1ng commented on CONTRIBUTING.md
> +1. `pull` 或 `rebase` 之后，如果有 conflicts，可以先使用 `git status` 查看存在 conflicts 的文件。修改成需要的版本后：
`pull --rebase` 我记得是不会的，它应该和 `rebase` 是一样的，所以后面说了，用 `rebase --continue`。容我回去确认下。

2018-07-24 02:37 UTC, huluoyang commented on CONTRIBUTING.md
> +    git fetch upstream
@S1ngS1ng  rebase 并不会 merge 啊，所以用 fetch 肯定不合理。

2018-07-24 02:40 UTC, huluoyang commented on CONTRIBUTING.md
> +1. `pull` 或 `rebase` 之后，如果有 conflicts，可以先使用 `git status` 查看存在 conflicts 的文件。修改成需要的版本后：
此处能够尽量减少操作是最好的，如果 --continue 能够解决就最好了。
目前我们的翻译流程依然不够简洁，中间也缺失关键步骤，这部分目前是靠个人的经验来弥补的。

2018-07-24 02:57 UTC, huluoyang commented on CONTRIBUTING.md
> +git checkout -b your_branch_name
关于是否应该简写，确实在不同的场景下应该有不同的做法。
为什么大家习惯 `git pull`，是因为这是一个单独的命令，从名字上就很好理解。
```
git add .
git commit -m "xxx"
```
为什么要建议分开写呢？ 因为这两步本来就代表不同的操作，用 `git commit -am "xxx"` 并没有简化用户思维，依然需要弄清参数 a 的意思。

`git checkout -b your_branch_name`
同理，这个操作对新手依然不友好，需要记忆参数 b 的意思。分两步写，新手一看就懂。

个人总结：如果有单独的命令来简化原来的多步操作，推荐用新的命令，反之，还是用多步操作。
试用前提：以上只针对新手，高手例外。

2018-07-24 03:04 UTC, huluoyang commented on CONTRIBUTING.md
> +# 或者你也可以打开你喜欢的编辑器（需要配置），在里面编写 commit message
OK，这部分，我同意你的意见。

你这个 alias，很有意思啊，确实能大幅提高 git 的操作效率，Mark it。

2018-07-24 05:41 UTC, S1ngS1ng commented on CONTRIBUTING.md
> +    git fetch upstream
@huluoyang 不是的。rebase 和 merge 是两个不同的做法。
上面的意思是，两种选择，要么 `git merge`，要么先 `git fetch upstream` 再 `git rebase upstream/translate`。
对于 `rebase`，当然要先 `fetch`

2018-07-24 05:43 UTC, S1ngS1ng commented on CONTRIBUTING.md
> +1. `pull` 或 `rebase` 之后，如果有 conflicts，可以先使用 `git status` 查看存在 conflicts 的文件。修改成需要的版本后：
@huluoyang 事实证明，可以的

2018-07-24 06:00 UTC, S1ngS1ng commented on CONTRIBUTING.md
> +- conflicts：合并冲突
@huluoyang 考虑了下，这里我觉得还是用“合并冲突”好些。
因为这里描述的内容都是和 git 相关的，上面的也是。
conflicts，在 git 中只以 merge conflicts 一种形式出现，哪怕 cherry-pick 产生的也叫 merge conflicts

2018-07-25 17:11 UTC, S1ngS1ng commented on CONTRIBUTING.md
> +        <li>如果 upstream 的 translate branch 有更新，你只需要在切换到 translate 分支之后，<code>git pull --rebase upstream/translate</code> 即可完成对本地 translate 分支的更新。再创建新的分支，就是基于 upstream 里最新的代码了，这样可以减少 conflicts 出现的可能</
Wrong path, pending update

2018-07-25 17:11 UTC, S1ngS1ng commented on CONTRIBUTING.md
> +    git pull --rebase upstream/translate
Ditto

2018-07-25 17:11 UTC, S1ngS1ng commented on CONTRIBUTING.md
> +    git config --global alias.gx 'pull --rebase upstream/translate'
Ditto

2018-07-25 17:13 UTC, S1ngS1ng commented on CONTRIBUTING.md
> +git add .        # 添加全部有改动的文件
Needs clarification for `.` and `-A` => FAQ

2018-07-25 17:14 UTC, S1ngS1ng commented on CONTRIBUTING.md
> +4. 更新（创建）PR 时，请更新 labels，方便管理
Pending removal

2018-07-26 09:59 UTC, merged

2018-07-26 09:59 UTC, huluoyang commented
我直接修改了下排版和符号的使用。