Translate basic-css
FreeCodeCampChina/challenges pull request #17
Opened 2018-07-23 16:25 UTC by silentsvv

### 翻译章节

《响应式网页设计——CSS 基础》

### 变更文件

- [x] basic-css.json

- [ ] basic-css.md

### 翻译进度 

- [x] 6/43

- [ ] 0%

2018-07-24 05:33 UTC, silentsvv commented
remark: 继续翻译3小节，进度6/43。

2018-07-24 22:20 UTC, S1ngS1ng requested changes
1. 注意标点和空格！请仔细检查下
2. `element` 优先翻译成`元素`，`tag` 优先翻译成`标签`。区别很简单，页面上、DOM 树里叫“元素”，代码中叫“标签”
3. 注意，`class`（类）是在 HTML 中定义的，而 CSS 只是起到选择作用，但并不定义 `class`。因此，CSS 中存在`类选择器`的说法，但不存在 `CSS 类`的说法。你可以 google 下 `CSS class`，看看结果
@huluoyang 
4. 这个 PR 的翻译内容可以截至这里，小问题比较多，请先把 comments 里提到的东西改了。后续的翻译可以开新的 PR 提交

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +        "我们通过修改<code>h2</code>标签里面的<code>样式</code>。",
`我们通过修改<code>h2</code>标签里面的<code>样式</code>。` =>
`可以通过修改 <code>h2</code> 标签的 <code>style</code> 来为 <code>h2</code> 添加样式。`

https://learn.freecodecamp.org/responsive-web-design/basic-css/change-the-color-of-text/

翻译的时候，记得去看下题目实际的样子。看到之后，就不会把 `style` 给翻译出来了。
就好像这里，你也不会把 `<code>h2</code>` 翻译成 `<code>二级标题</code>`

--------

参考微信群，昨天说了，行内元素（比如 `<code></code>`）是否加空格取决与内容，`h2` 是半角字符，外面是全角，所以需要加空格

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +        "负责标签文本的颜色属性是<code>color</code>。",
`负责标签文本的颜色属性` 建议 => 
`负责控制元素文本颜色的属性`

-------

需要加空格。下同

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +        "这是改变<code>h2</code>标签为蓝色的方法:",
结尾用全角冒号，下同

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +        "尝试改变<code>h2</code>文本标签的颜色为红色。"
之前都是介绍。
既然这里是描述题目的，建议：
`请把 <code>h2</code> 的文本颜色设置为红色。`

（因为本身 h2 没有设置颜色，所以不存在“改”的说法

下同

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +          "text": "你的行内<code>样式</code>应该以<code>;</code>结束。",
`你的行内<code>样式</code>应该以<code>;</code>结束。` =>
`你的行内样式应该以 <code>;</code> 结束。`

或

`<code>h2</code> 元素 <code>style</code> 属性的值应该以 <code>;</code> 结束。`

你来选吧

记得下一行同步更新

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +        "当你输入<code>&#60;h2 style=\"color: red\"&#62;CatPhotoApp&#60;/h2&#62;</code>, 设置<code>行内样式</code>来改变单独的<code>h2</code>标签的样式，这是改变<code>层叠样式表(CSS)</code>的方法之一。",
应该使用全角逗号，全角括号

----------

`设置<code>行内样式</code>来改变单独的<code>h2</code>标签的样式` =>
`你就通过 <code>inline CSS</code> 的方式改变了 <code>h2</code> 元素的外观。其中，CSS 指的是<code>层叠样式表</code>。`

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +        "在CSS中, 有上百种<code>属性</code>可以让你改变页面样式。",
CSS 后面加空格

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +        "这是改变标签样式的一个特别方法, 不过存在着更好的方法来改变<code>层叠样式表(CSS)</code>。",
`标签` => `元素`

后面遇到 `element`，优先翻译成`元素`

-------

全角括号

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +        "在style样式声明区域内, 可以创建一个<code>CSS选择器</code>的规则来应用于所有的<code>h2</code>标签。例如，如果你想所有<code>h2</code>标签变成红色, 可以添加下方的样式规则:",
全角逗号，结尾全角冒号

-----

`CSS选择器` => `CSS 选择器`

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +        "注意，在每个元素的样式声明区域里，打开和关闭花括号（<code>{</code>和<code>}</code>）非常重要。你需要确定你定义的样式规则位于花括号之间。最后，请确定每个已定义的元素样式规则的末尾添加'分号'。",
`打开和关闭花括号（<code>{</code>和<code>}</code>）非常重要` => 
`左右花括号（<code>{</code> 和 <code>}</code>）一定要写全`

-------

`最后，请确定每个已定义的元素样式规则的末尾添加'分号'。` =>
`以及，一定要在每个元素样式规则的末尾添加分号。`
或
`以及，记得在每个元素样式规则的末尾添加分号。`
或
`以及，请确定每个元素样式规则的末尾都添加了分号。`

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +        "删除<code>h2</code>标签的行内样式，通过创建<code>style</code>样式声明区域. 添加CSS样式规则使<code>h2</code>标签变为蓝色。"
`通过` 删掉。。

------

全角句号

------

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +          "text": "移除<code>h2</code>标签的style行内样式。",
`移除 <code>h2</code> 元素的行内样式。`

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +        "CSS的类具有可重用性，可应用于各种HTML标签。",
建议：`CSS 的类（class）具有可复用性`

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +        "一个CSS类声明示例，如下所示：",
见 Review comment

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +        "注意你的<code>style</code>样式声明，CSS类名需以句号开头。而在你的HTML标签里的Class属性, CSS类则不需要包含句号",
这里的 `Class` 不可以大写。建议 ` <code>class</code> `

------

`句号` 建议 => `英文句号` 或 `英文句点`

参考：https://zh.wikipedia.org/wiki/%E5%8F%A5%E5%8F%B7

-----

`CSS类则不需要包含句号` 这里应该说 `类名不需要包含句号`

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +        "在<code>style</code>样式声明里，改变<code>h2</code>标签选择器名为<code>.red-text</code>的一个CSS类，同时将颜色<code>blue</code>变为<code>red</code>。",
`改变<code>h2</code>标签选择器名为<code>.red-text</code>的一个CSS类，` =>
`把标签选择器 <code>h2</code> 改为类选择器 <code>.red-text</code>，`

参考 https://learn.freecodecamp.org/responsive-web-design/basic-css/use-a-css-class-to-style-an-element/

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +        "在你的<code>h2</code>html标签里，添加一个<code>class</code>属性<code>，且值为<code>'red-text'</code>."
全角句号。

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +          "testString": "assert($(\"h2\").attr(\"style\") === undefined, '不要使用<code>style=\"color&#58; red\"</code>的行内样式，在你的<code>h2</code>标签里。');"
注意语序。

`不要在 <code>h2</code> 标签里使用 <code>style=\"color&#58; red\"</code> 这样的行内样式。`

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +          "text": "你的<code>h2</code>标签应该包含一个名为<code>red-text</code>的class属性值。",
`你的<code>h2</code>标签应该包含一个名为<code>red-text</code>的class属性值。` =>

`你的 <code>h2</code> 元素的类应为 <code>red-text</code>。`

下同

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +          "testString": "assert(code.match(/\\.red-text\\s*\\{\\s*color\\s*:\\s*red;\\s*\\}/g), '你的style样式声明区域里应该包含一个<code>red-text</code>CSS类规则，并且它的样式应为红色。');"
`它的样式应为红色` =>
`它的颜色应为红色`

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +        "通过CSS类,多个HTML标签上可以使用相同的cSS样式规则。你可以将<code>red-text</code>CSS类应用在第一个<code>p</code>标签上。"
这个 class 显然是在 HTML 定义的。见 Review comment

-------

全角逗号

-------

`cSS ` => `CSS` 🤦‍♂️ 

------

请把 `<code>red-text</code>` 类添加给第一个 `p` 标签。

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +        "你可以设置标签里面的字体，通过<code>font-family</code>属性。",
注意语序

2018-07-24 22:20 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +          "text": "在<code>style</code>样式声明区域里，设置<code>p</code>元素的<code>font-size</code>为<code>16px</code>。浏览器和文本缩放应设置为100％。",
`设置<code>p</code>元素的<code>font-size</code>为<code>16px</code>。` =>

`<code>p</code> 元素的 <code>font-size</code> 值应为 <code>16px</code>。`

下同

2018-07-27 05:07 UTC, silentsvv commented
已处理。

2018-07-27 06:02 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +          "testString": "assert($(\"h2\").attr(\"style\") === undefined, '不要在 <code>h2</code> 元素里使用 <code>style=\"color&#58; red\"</code> 的行内样式 。');"
这里多了个空格

2018-07-27 06:02 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-css.json
> +        "注意你的 <code>style</code> 样式区域声明里，<code>class</code> 需以句号开头。而在你的HTML元素里的 <code>class</code> 属性的类名，不需要包含句号",
结尾句号

2018-07-27 06:03 UTC, S1ngS1ng approved these changes
两个小问题改下。其他都 OK 👍

2018-07-28 09:14 UTC, huluoyang commented
🎉恭喜泽晴的第一个 PR 成功被 merge 进仓库， keep moving。

2018-07-28 09:14 UTC, merged