responsive-web-design-projects_part1
FreeCodeCampChina/challenges pull request #2
Opened 2018-07-19 12:03 UTC by XERO75

2018-07-22 10:14 UTC, S1ngS1ng requested changes
1. 根据群里的讨论，`您` => `你`
2. 注意标点和空格
3. 注意拼写，英文部分与原文一致即可

2018-07-22 10:14 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-projects.json
> +        "满足以下 <a href='https://en.wikipedia.org/wiki/User_story' target='_blank'>用户故事</a> 并且通过所有的测试，你可以根据自己喜好装饰它",
整句建议：
`在满足以下 <a href='https://en.wikipedia.org/wiki/User_story' target='_blank'>用户故事</a> 并能通过所有测试的前提下，你可以根据自己的喜好来美化你的 app。`

注意结尾要加句号

2018-07-22 10:14 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-projects.json
> +        "您可以使用 HTML、JavaScript 以及 CSS 来完成项目，因为这是目前这节课所涉及的内容，我们推荐使用纯CSS代码，建议当前应多练习纯CSS。您也可以使用Bootstrap 或者是 SASS。一些别的技术（例如JQurey、React、Angular 或者是 VUE）在当前的项目是不推荐的，因为可能会有无法预知的错误，但在别的项目中我们仍有机会去使用不同的技术栈比如
`您` => `你`。下同

-------

`，因为这是目前这节课所涉及的内容，我们推荐使用纯CSS代码，` 建议 =>
`。由于目前我们只学到了 CSS，因此建议你只使用 CSS 完成这个项目，顺便还可以巩固一下之前学到的内容。`

-------

`纯CSS代码`、`纯CSS`、`使用Bootstrap` 请添加空格

--------

`JQurey`、`VUE` 这样的拼写是错误的。请参考原文，或官网。

-------

`一些别的技术（……）在当前的项目是不推荐的` 建议 =>
`在当前的项目中，不推荐使用其他技术，如 ……。`

--------

`因为可能会有无法预知的错误` =>
`因为一旦出现问题，你可能要花很多时间去修复。`

注意词组 `at your own risk` 的意思，不是表示 “会有问题”，而是强调 “一旦出现问题，由本人承担” 这种意思。我提供的翻译也不够好，你再考虑下吧

-------

`我们会接受并尽力去处理在使用建议的技术栈出现的问题` =>
`我们会接受并尽力处理你在使用建议的技术栈过程中遇到的问题`

2018-07-22 10:14 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-projects.json
> +        "<strong>用户故事 #1:</strong> 我的致敬页应有对应 <code>id=\"main\"</code> 的元素, 其中包含其他的所有元素",
应该使用全角逗号和冒号。下同。
结尾要加句号

2018-07-22 10:14 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-projects.json
> +        "<strong>用户故事 #2:</strong> 我应该看到一个具有相应 <code>id=\"title\"</code> 的元素, 其中包含描述致敬页主题的字符串 (即文本) (如 \"Dr. Norman Borlaug\")。",
` (如 \"Dr. Norman Borlaug\")。` 建议 =>
`，如 \"Dr. Norman Borlaug\"。`

2018-07-22 10:14 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-projects.json
> +        "<strong>用户故事 #5:</strong> 在 <code>img-div</code> 元素内，我应该看见一个具有相应 <code>id=\"img-caption\"</code> 的元素，其中包含描述 <code>img-div</code> 中显示的图像文本的文本。",
`其中包含描述 <code>img-div</code> 中显示的图像文本的文本。` =>
`其中包含对 <code>img-div</code> 中图像的描述。`

2018-07-22 10:14 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-projects.json
> +        "<strong>用户故事 #7:</strong> 我应该看见具有对应 <code>id=\"tribute-link\"</code> 的元素，它链接到一个包含有关致敬页主题的其他信息的外部网页，提示: 你必须为元素提供 <code>target</code> 属性，并设置为 <code>_blank</code> 以便在新选项卡中打开连接 (例 <code>target=\
`包含有关致敬页主题的其他信息的外部网页` =>
`包含有关致敬页主题额外信息的外部网页`

---------

结尾应该使用全角句号

2018-07-22 10:14 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-projects.json
> +        "要是卡住的话，记得使用 <a href='https://forum.freecodecamp.org/t/how-to-get-help-when-you-are-stuck/19514' target='_blank'>Read-Search-Ask</a> 方法。"
建议删掉 `方法`

2018-07-22 14:38 UTC, huluoyang commented on 01-responsive-web-design/responsive-web-design-projects.json
> +        "<strong>用户故事 #7:</strong> 我应该看见具有对应 <code>id=\"tribute-link\"</code> 的元素，它链接到一个包含有关致敬页主题的其他信息的外部网页，提示: 你必须为元素提供 <code>target</code> 属性，并设置为 <code>_blank</code> 以便在新选项卡中打开连接 (例 <code>target=\
[user story](https://zh.wikipedia.org/wiki/%E7%94%A8%E6%88%B7%E6%95%85%E4%BA%8B) 翻译成用户故事只是直译，也就是字面上的意思。

但在项目这个场景下，user story 应该是功能或需求的意思。

2018-07-22 14:47 UTC, huluoyang commented on 01-responsive-web-design/responsive-web-design-projects.json
> +        "您可以使用 HTML、JavaScript 以及 CSS 来完成项目，因为这是目前这节课所涉及的内容，我们推荐使用纯CSS代码，建议当前应多练习纯CSS。您也可以使用Bootstrap 或者是 SASS。一些别的技术（例如JQurey、React、Angular 或者是 VUE）在当前的项目是不推荐的，因为可能会有无法预知的错误，但在别的项目中我们仍有机会去使用不同的技术栈比如
at your own risk => 在你自己的风险（有道翻译）

at your own risk => 一旦出现问题，由本人承担。（整体意思对了，但不够简洁）

at your own risk => 风险自担（用户熟悉、一看就懂）

翻译追求的是整体意思的把控，而不是字面意思。

中文有很多大家熟悉的成语、短语可以轻松表达这类意思。

2018-07-22 19:33 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-projects.json
> +        "<strong>用户故事 #7:</strong> 我应该看见具有对应 <code>id=\"tribute-link\"</code> 的元素，它链接到一个包含有关致敬页主题的其他信息的外部网页，提示: 你必须为元素提供 <code>target</code> 属性，并设置为 <code>_blank</code> 以便在新选项卡中打开连接 (例 <code>target=\
@huluoyang 我其实一开始加了这个 comment，打开 Wikipedia 之后我就把 comment 删了 😂 
我一开始想建议的是“用户需求”或“功能”

2018-07-24 06:34 UTC, S1ngS1ng requested changes
请更新下。注意统一格式和翻译

2018-07-24 06:34 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-projects.json
> +        "<strong>用户故事^#1：</strong> 我的致敬页应有对应 <code>id=\"main\"</code> 的元素， 其中包含其他的所有元素",
群里说的意思是：`^` 代表空格。。不是加上 `^`

2018-07-24 06:34 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-projects.json
> +        "<strong>目标：</strong> 使用 <a href='https://codepen.io' target='_blank'>CodePen.io</a> 搭建一个与这个功能上相似的 app： <a href='https://codepen.io/freeCodeCamp/full/zNqgVx' target='_blank'>https://codepen.i
参考群内的讨论。行内元素（比如 a）两边是否加空格取决于内容。这里，因为是在全角冒号之后，所以不需要加

2018-07-24 06:34 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-projects.json
> +        "在满足以下 <a href='https://en.wikipedia.org/wiki/User_story' target='_blank'>用户故事</a> 并能通过所有测试的前提下，你可以根据自己的喜好来美化你的 app。",
这里同理：
错误：
![image](https://user-images.githubusercontent.com/13592559/43120878-8fd3e3f6-8ed0-11e8-8744-7fa3758af873.png)

正确：
![image](https://user-images.githubusercontent.com/13592559/43120866-877ab086-8ed0-11e8-8bca-52a358fcfc86.png)

2018-07-24 06:34 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-projects.json
> +        "<strong>用户故事^#2：</strong> 我应该看到一个具有相应 <code>id=\"title\"</code> 的元素， 其中包含描述致敬页主题的字符串 (即文本)，如 \"Dr. Norman Borlaug\"。",
strong 也是一样

2018-07-24 06:34 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-projects.json
> +        "<strong>用户故事^#3：</strong> 我应该看到一个带有对应 <code>id=\"img-div\"</code> 的 <code>div</code> 元素。",
这里的 code 加空格是对的。因为内容是半角，两边是全角

2018-07-24 06:34 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-projects.json
> +        "完成项目并通过所有测试后， 输入你的项目在 CodePen 上的链接。",
多余的空格

2018-07-24 06:34 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-projects.json
> +        "<strong>用户故事^#4：</strong> 在 form 元素内， 我需要在 <code>id=\"name\"</code> 的字段中输入我的名字。",
多余的空格。下同

2018-07-26 05:36 UTC, S1ngS1ng approved these changes

2018-07-28 08:46 UTC, huluoyang commented
🎉 恭喜良良的第一个PR成功进入仓库，Mission is impossible!

2018-07-28 08:46 UTC, merged