Translate debugging
FreeCodeCampChina/challenges pull request #22
Opened 2018-07-25 08:59 UTC by CatcherO

### 翻译章节
《算法和数据结构——调试》
### 变更文件

- [x] debugging.json

- [ ] debugging.md
### 翻译进度

- [x] 100% 

- [x] 0%

2018-08-01 09:26 UTC, huluoyang commented
整体翻译很不错，稍微调整下语序就完美了，另外请记得翻译 debugging.md。

2018-08-01 09:26 UTC, huluoyang requested changes

2018-08-01 09:26 UTC, huluoyang commented on 02-javascript-algorithms-and-data-structures/debugging.json
> +          "text": "你的代码应该在循环的终止条件中修复比较运算符。",
your code => 你
此处应全局替换
```
Your code should fix the comparison operator in the terminal condition of the loop.
你应该修改比较运算符来避免出现死循环。
```

2018-08-01 13:50 UTC, CatcherO commented on 02-javascript-algorithms-and-data-structures/debugging.json
> +          "text": "你的代码应该在循环的终止条件中修复比较运算符。",
恩，太“翻译腔”了 :joy:

2018-08-01 18:40 UTC, S1ngS1ng requested changes
一点点格式的问题。内容 OK 的 👍

2018-08-01 18:40 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/debugging.json
> +        "Chrome 和 Firefox 都有出色的 JavaScript 控制台，也称为 DevTools，用于调试你的 JavaScript 代码。",
建议：
`Chrome 和 Firefox 都有出色的 JavaScript 控制台（也称为 DevTools），可以用来调试你的 JavaScript 代码。`

2018-08-01 18:40 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/debugging.json
> +        "你可以在 Chrome 的菜单中找到“开发者工具”或 FireFox 的菜单中的“ Web 控制台”。如果你使用其他浏览器或手机，我们强烈建议你切换到桌面版 Firefox 或 Chrome。",
个人觉得 `Web` 前面的空格应该加到引号外面。`Web` 后面的空格你加的没错

现在：
![image](https://user-images.githubusercontent.com/13592559/43540423-89e7d454-957c-11e8-96c3-de50c30a2204.png)


建议：
![image](https://user-images.githubusercontent.com/13592559/43540443-9b3edcca-957c-11e8-81b0-0609940badf9.png)

2018-08-01 18:40 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/debugging.json
> +        "<code>console.log()</code>方法可能是最有用的调试工具，它可以将括号中的内容输出到控制台，将它放在代码中的关键点可以显示变量的中间值。在查看输出之前，最好先了解输出应该是什么。在整个代码中使用检查点来查看计算状态将有助于缩小问题所在。",
`变量的中间值` => `变量在当时的值`

我感觉这个 intermediate 指的是执行过程中。你来决定怎么翻译好吧

------

`在查看输出之前，最好先了解输出应该是什么。` =>
`在查看输出之前，最好先想清楚输出应该是什么。`

2018-08-01 18:40 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/debugging.json
> +        "下面是输出 'Hello world！' 到控制台的示例：",
这个叹号是不该用全角的，这是个 string

2018-08-01 18:40 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/debugging.json
> +        "你可能已经注意到一些 freeCodeCamp JavaScript 的挑战有他们自己的控制台。这些控制台的行为与你在上一次挑战中使用的浏览器控制台略有不同。",
建议去掉 `他们`

2018-08-01 18:40 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/debugging.json
> +        "分支程序，即在满足某些条件时执行不同操作的程序，依赖于 JavaScript中的<code>if</code>，<code>else if</code>和<code>else</code>语句。条件有时采取测试一个结果是否等于一个值的形式。",
`JavaScript` 之后加上空格

列举的时候，逗号应该改成顿号，去掉`和`

2018-08-01 18:40 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/debugging.json
> +        "当你试图访问字符串或数组的特定索引（分割或访问一个片段）或循环索引时，有时会出现<code>Off by one errors</code>错误（有时称为 OBOE）。 JavaScript 索引从<code>0</code>开始，而不是<code>1</code>，这意味着最后一个索引总会比字符串或数组的长度少 1。 如果你尝试访问等于长度的索引，程序可能会抛出“索引超出范围
句号之后多了个空格，两处

2018-08-01 18:40 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/debugging.json
> +        "以下函数应该创建一个具有<code>m</code>行和<code>n</code>列“零”的二维数组。不幸的是，它没有产生预期的输出，因为<code>row</code>变量没有在外部循环中重新初始化（设置回空数组）。修改代码，使其正确地返回包含 3 行 2 列“零”的二维数组，即<code>[[0,0]，[0,0]，[0,0]]</code>。"
`code` 里面的逗号应该保持英文的（否则这段代码就有问题了），不应该用全角。以及，后面要加空格。
用原文的就好

2018-08-01 18:40 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/debugging.json
> +        "<code>myFunc()</code>函数包含一个无限循环，因为终止条件<code>i != 4</code>永远不会为<code>false</code>(并中断循环) -<code>i</code>将每次递增2，然后跳过4，因为<code>i</code>是从奇数开始递增。在终端条件中输入比较运算符，使循环仅在<code>i</code>小于或等于4的情况下运行。"
数字要加空格（逗号前的不用加）。参考 style-guide
`递增 2，然后跳过 4，`
`小于或等于 4 的情况`

2018-08-03 17:23 UTC, S1ngS1ng approved these changes
Thanks 👍

2018-08-04 07:44 UTC, CatcherO commented on 02-javascript-algorithms-and-data-structures/debugging.md
> +调试会让人抓狂，但它有助于开发（并遵循）逐步审查代码的方法。检查变量在程序运行过程中的值和类型是否正确。你可以从一个简单的消除过程开始。
这句不知道怎么翻才好 🤒 ...

2018-08-04 13:07 UTC, huluoyang commented on 02-javascript-algorithms-and-data-structures/debugging.md
> +调试会让人抓狂，但它有助于开发（并遵循）逐步审查代码的方法。检查变量在程序运行过程中的值和类型是否正确。你可以从一个简单的消除过程开始。
是有点不好翻译，我尝试了下，你看看如何：
调试本身总是令人沮丧的，但它有助于让你学会一种逐步检查代码的方法。这意味着你要去检查中间值和变量类型，看看它们是否是你所期望的。在这过程中，运用排除法，你很快就能找到问题的所在。

2018-08-05 06:56 UTC, S1ngS1ng commented
@CatcherO 内容上没问题了。不过你的 commit history 乱了 😂 
参考一下 https://github.com/FreeCodeCampChina/challenges/blob/translate/CONTRIBUTING.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98 的最后一个问题。记得不要混用 `git pull` 和 `git pull --rebase`。
如果解决不了，微信加我私聊

2018-08-06 03:47 UTC, S1ngS1ng commented
Changes addressed in #60

2018-08-06 03:47 UTC, closed without merging