Translate basic-node-and-express
FreeCodeCampChina/challenges pull request #26
Opened 2018-07-26 15:28 UTC by ifyour

### 翻译章节

《API 和 微服务—— Node 和 Express 基础》

### 变更文件

- [x] basic-node-and-express.json

- [ ] basic-node-and-express.md

### 翻译进度 

- [x] 60%

- [ ] 0%

2018-07-28 10:09 UTC, huluoyang requested changes

2018-07-28 10:09 UTC, huluoyang commented on 05-apis-and-microservices/basic-node-and-express.json
> +        "在开发中，能够检查代码发生变化这非常重要。Node 只是一个 JavaScript 环境。与客户端 JavaScript 一样，你可以使用控制台输出有用的调试信息。在本地计算机上，你可以在终端中输出调试信息。在 Glitch 上，你可以打开屏幕下方的日志。使用 \"Logs\" 按钮切换日志面板（在左上角，应用名称的下面）。",
`During the development process, it is important to be able to check what’s going on in your code.`
`在开发中，能够检查代码发生变化这非常重要。`
代码发生变化和控制台有什么关系？
看看这样是不是更准确些：
`在开发过程中，能够随时看到代码的运行结果是非常重要的。`

2018-07-28 10:09 UTC, huluoyang commented on 05-apis-and-microservices/basic-node-and-express.json
> +          "text": "应该在控制台中打印出 <code>\"Hello World\"</code>",
这样会不会好点：
`控制台应该输出：<code>\"Hello World\"</code>"`

2018-07-28 10:09 UTC, huluoyang commented on 05-apis-and-microservices/basic-node-and-express.json
> +        "我们来让服务器输出第一个字符串！在 Express 中，路由采用这种结构：<code>app.METHOD(PATH, HANDLER)</code>。<code>METHOD</code> 是小写的 http 方法。<code>PATH</code> 是服务器上的相对路径（它是一个字符串，甚至是正则表达式）<code>HANDLER</code> 是 Express 匹配路由
let's == let us 让我们

2018-07-28 10:09 UTC, huluoyang commented on 05-apis-and-microservices/basic-node-and-express.json
> +          "text": "应用应该响应 'Hello Express' 字符串",
app  保留原文不翻译
serve 的翻译应该和你上面保存一致。
`app 应该输出 'Hello Express'  字符串。`

2018-08-01 04:42 UTC, S1ngS1ng requested changes
注意 `<code>` 两边不加空格，任何时候都不加

2018-08-01 04:42 UTC, S1ngS1ng commented on 05-apis-and-microservices/basic-node-and-express.json
> +        "HTML 服务器返回 HTML，API 服务器返回处理的数据。<dfn>REST</dfn>（表现层状态转换）API 允许使用更简易的方式交换数据，从而不需要客户端知道服务器的实现细节。客户端只需要通过 URL 知道请求的资源在哪，以及需要对请求的数据进行何种动作。比如 GET 这个动作，就是从服务器上获取某些信息，它不会修改任何数据。如今，在 web 上传输数据的首选数据格式
`HTML 服务器返回 HTML，API 服务器返回处理的数据。` 建议 =>
`HTML 服务器提供 HTML，API 服务器提供数据。`

--------

`客户端只需要通过 URL 知道请求的资源在哪，以及需要对请求的数据进行何种动作。` =>
`客户端只要知道需请求资源对应的 URL 是什么，以及需要对这个 URL 进行何种操作就够了。`

注意，不是通过 URL 知道资源在哪儿，而是资源就是 URL。以及，不是对数据进行操作，而是对 URL 进行操作

------

2018-08-01 04:42 UTC, S1ngS1ng commented on 05-apis-and-microservices/basic-node-and-express.json
> +        "我们来创建一个简单的 API，通过创建一个简易的路由 <code>/json</code>，当客户端请求这个路由时，返回一个 JSON 数据。你可以像之前那样通过 <code>app.get()</code> 方法来做。在路由处理程序中使用 <code>res.json()</code> 方法返回 JSON 格式的数据，只需要给它传一个对象作为参数。这个方法会结束请求响应循环（
`route that responds with JSON at the path <code>/json</code>`：
`一个路径为<code>/json</code>且返回数据是 JSON 格式的路由`，`path` 为 `/json`，而不是路由是 `/json`

------

`。在路由处理程序中使用 <code>res.json()</code> 方法返回 JSON 格式的数据，只需要给它传一个对象作为参数。` 不通顺，注意这部分是承接上文的，而且 `passing` 是对前面的修饰。可以翻译成：
`，然后在路由处理部分使用<code>res.json()</code>方法返回 JSON 格式的数据，这个方法可以接收一个配置对象。`

https://expressjs.com/en/api.html

------

`将以它们的实际值为准（转成字符串）。` =>
`会以它们的执行结果为基准，再转成字符串。`

2018-08-03 06:53 UTC, S1ngS1ng commented on 05-apis-and-microservices/basic-node-and-express.json
> +        "处理函数采用这种形式：<code>function(req, res) {...}</code>，在这个处理函数的参数中 <code>req</code>and 是请求对象。<code>res</code> 是响应对象。举个例子，处理函数：",
` <code>req</code>` 前面多了个空格。

后面的 and 删掉。

2018-08-03 06:55 UTC, S1ngS1ng approved these changes
底下还有很多地方 `<code>` 前面多了个空格。
有个 `and` 多余的。
请尽快修改下，别的没问题，先 approve 了

2018-08-03 06:55 UTC, S1ngS1ng commented on 05-apis-and-microservices/basic-node-and-express.json
> +        "当 GET 请求根路由（ \"/\" ）时，使用 <code>app.get()</code> 方法端响应一个 \"Hello Express\" 字符串。在 Glitch 中点击 \"Show Live\" 按钮，通过查看日志确保你的代码正常运行，然后在浏览器中查看结果。"
`<code>` 前面多了个空格

2018-08-06 14:44 UTC, ifyour commented
我先暂时批量替换了`<code>code</code>`前后的空格，下面还未翻译小节不用 review。🙂

2018-08-06 21:49 UTC, S1ngS1ng commented
Thanks 👍

2018-08-07 08:44 UTC, merged