Translation of document "regular-expressions", 20% completed！
FreeCodeCampChina/challenges pull request #3
Opened 2018-07-19 14:33 UTC by Robin-zero

2018-07-22 21:43 UTC, S1ngS1ng requested changes
关于 `match`，`search` 和 `find`，你给出了多种翻译。其实应该统一一下的。

还有 `test`。`test` 是 RegExp 的方法，因此发起者应为一个正则表达式。而 `search` 和 `match` 均为字符串的方法，发起者应为字符串。

还有 `find`，和 `look for`。这里的语序你翻译的没错：
![image](https://user-images.githubusercontent.com/13592559/43050092-1f5e5ec6-8db8-11e8-9d19-b9a35599c938.png)

`find` 不是字符串或 RegExp 的方法，直接翻译成 `匹配到` 或 `找到` 应该就够了。
`match` 也是一样，翻译成 `匹配到` 就好。
`search` 你翻译的是 `搜索`，我感觉可以；但有时可能换成 `搜寻` 通顺些。比如：

![image](https://user-images.githubusercontent.com/13592559/43050188-9b1be550-8db9-11e8-8eb2-76fc71928a1d.png)

后两个用`搜寻`，个人感觉好些。注意语序。

而 `test`是用来验证是否通过 pattern 里定义的规则的测试，所以翻译成 `检测` 会不会好些？

类似的评论我就不再在 diff 里 comment 了。你更新之后仔细检查一下前后文吧

-------

建议 `pattern` 翻译为 `规则` 或 `匹配规则` 就好。不要翻译成 `模式`

---------

全篇你的 `您` => `你`

---------

我现在 review 到了 161 行。因为改动比较多，请先修改，然后检查一下标点和空格，以及通篇翻译是否通顺

2018-07-22 21:43 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/regular-expressions.json
> +        "在编程语言中，正则表达式用于匹配指定的字符串。通过正则表达式创建模式（规则）可以帮你完成指定匹配。",
`模式` 建议 =>
 `匹配模式`

-------

`你可以通过创建匹配模式（规则）来匹配字符串中指定的部分。`

2018-07-22 21:43 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/regular-expressions.json
> +        "JavaScript中有多种使用正则表达式的方法。测试正则表达式的一种方法是使用 <code>.test()</code> 方法。<code>.test()</code> 方法会把你编写的正则表达式应用到一个字符串（即括号内的内容），如果你的模式成功匹配到字符，则返回 <code>true</code>，反之，返回 <code>false</code>。",
`JavaScript` 之后应该加上空格

-------

`你的模式` 建议 =>
`你定义的规则`

2018-07-22 21:43 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/regular-expressions.json
> +        "使用 <code>.test()</code> 方法把正则表达式 <code>myRegex</code> 应用到字符串 <code>myString</code> 上面。"
`使用 <code>.test()</code> 方法把正则表达式 <code>myRegex</code> 应用到字符串 <code>myString</code> 上面。` 建议 =>
`使用 <code>.test()</code> 方法，测试字符串 <code>myString</code> 是否符合正则表达式 <code>myRegex</code> 定义的规则。`

这样会不会通顺些？你决定吧

2018-07-22 21:43 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/regular-expressions.json
> +          "testString": "assert(result === true, '你的返回结果应该为 <code>true</code>.');"
这两行，结尾应该是全角句号。

2018-07-22 21:43 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/regular-expressions.json
> +        "任何其他形式的 <code>\"Kevin\"</code> 都不会被匹配。例如，正则表达式 <code>/Kevin/</code> 不会匹配 <code>\"kevin\"</code> 或者 <code>\"KEVIN\"</code> 。",
结尾句号之前多了个空格。

2018-07-22 21:43 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/regular-expressions.json
> +        "未来的挑战将为你展示如何匹配其他形式的字符串",
结尾句号

------

`未来` 建议 => `后续` 或者 `后面`

2018-07-22 21:43 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/regular-expressions.json
> +          "text": "你的正则表达式 <code>waldoRegex</code> 应该找到 <code>\"Waldo\"</code>",
结尾句号

2018-07-22 21:43 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/regular-expressions.json
> +        "在上一个挑战中，你使用正则表达式 <code>/Hello/</code> 搜索到了字符串 <code>\"Hello\"</code>。那个字符串搜索字符串 <code>\"Hello\"</code> 的文字匹配。下面是另一个搜索字符串 <code>\"Kevin\"</code> 文字匹配的示例：",
`那个字符串搜索字符串 <code>\"Hello\"</code> 的文字匹配。` 

这句不通顺。其实可以去掉，因为 `搜索到了` 已经基本包含了原文 `That regex searched for a literal match of the string <code>\"Hello\"</code>.` 这句话的意思

----------------

`那个字符串搜索字符串 <code>\"Hello\"</code> 的文字匹配` =>

`那个正则表达式在字符串中搜寻 <code>\"Hello\"</code> 的文字匹配`

注意主语

---------

`下面是另一个搜索字符串 <code>\"Kevin\"</code> 文字匹配的示例：` =>
`下面是另一个在字符串中搜寻 <code>\"Kevin\"</code> 的示例：`

2018-07-22 21:43 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/regular-expressions.json
> +        "完成正则表达式 <code>waldoRegex</code> ，在字符串 <code>waldoIsHiding</code> 中找到匹配文字 <code>\"Waldo\"</code> 。"
这里的逗号前不应该有空格

-------

`找到匹配文字` =>

~~`找到文本` 或 `匹配到文本`。选一个。下同。~~ => 参考 review 的 comment

而且，其他部分也请保持同步

2018-07-22 21:43 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/regular-expressions.json
> +        "这对于搜索单个字符串非常有用，但仅限于一种模式。您可以使用 <code>alternation</code> 或者 <code>OR</code> 操作符：<code>|</code> 。",
`您可以使用 <code>alternation</code> 或者 <code>OR</code> 操作符：<code>|</code> 。` =>

`你可以使用 <code>|</code> 操作符来匹配多个规则。`

原文 `alternation` 和 `OR` 都只是英文里对 `|` 的称呼。不好翻译可以不翻

2018-07-22 21:43 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/regular-expressions.json
> +        "你还可以搜索不止两个模式。你可以通过添加更多的模式来实现这一功能，这些模式将包含更多的 <code>OR</code> 操作符来分隔它们，比如 <code>/yes|no|maybe/</code> 。",
`<code>OR</code>` => `<code>|</code>`

2018-07-22 21:43 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/regular-expressions.json
> +        "完成正则表达式 <code>petRegex</code> 匹配 <code>\"dog\"</code> 、<code>\"cat\"</code> 、<code>\"bird\"</code> 或者 <code>\"fish\"</code> 。"
`完成正则表达式 <code>petRegex</code> 匹配……` => `完成正则表达式 <code>petRegex</code>，让它可以匹配到……`

2018-07-22 21:43 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/regular-expressions.json
> +          "text": "对于字符串 <code>\"John has a pet dog.\"</code>，你的正则表达式 <code>petRegex</code> 应该返回 <code>true</code> 。",
这里的表述都不太好。返回 `true` 的不是 `petRegex`，而应该是 `petRegex.test()`。

因此，要么说：
`对于字符串 <code>\"John has a pet dog.\"</code>，你的正则表达式 <code>petRegex</code> 的 <code>test</code> 方法应该返回 <code>true</code> 。`
或者说：`字符串 <code>\"John has a pet dog.\"</code> 应该可以通过正则表达式 <code>petRegex</code> 的测试。`

下同。选一个一起改吧，或者如果你有更好的表达方式也可以

2018-07-22 21:43 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/regular-expressions.json
> +        "到目前为止，你已经查看了利用正则表达式来执行字符串的文字匹配。但是有时候，你可能也想匹配不同的情况。",
这里的 `case` 不是情况，是英文字母大小写

2018-07-22 21:43 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/regular-expressions.json
> +        "大小写（或者字母大小写）是大写字母和小写字母的区别。大写字母的例子有 <code>\"A\"</code> 、<code>\"B\"</code> 和 <code>\"C\"</code>。小写字母的例子有 <code>\"a\"</code> 、<code>\"b\"</code> 和 <code>\"c\"</code> 。",
删掉全角标点前，半角字符后的空格。

这样是对的：
![image](https://user-images.githubusercontent.com/13592559/43050390-b5271822-8dbc-11e8-968a-8d69506e6f2f.png)

这样就是错的：
![image](https://user-images.githubusercontent.com/13592559/43050393-c61af32e-8dbc-11e8-9316-9353459d0841.png)

2018-07-22 21:43 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/regular-expressions.json
> +        "你可以使用所谓的模式修正符来匹配这两种情况。有许多其他标志，不过这里主要关注忽略大小写的模式修正符 - <code>i</code> 模式修正符。你可以通过将它附加到正则表达式之后来使用它。这里给出使用该模式修正符的一个实例 <code>/ignorecase/i</code>。这个字符串可以匹配字符串 <code>\"ignorecase\"</code> 、<code>\"
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp

flag：标志

------

同样，有多余的空格

2018-07-23 15:31 UTC, Robin-zero commented on 02-javascript-algorithms-and-data-structures/regular-expressions.json
> +          "text": "你的正则表达式 <code>waldoRegex</code> 应该找到 <code>\"Waldo\"</code>",
原文没有句号的也要加上嘛？

2018-07-29 16:08 UTC, S1ngS1ng commented
@Robin-zero 看下 comments，记得更新

2018-07-31 17:02 UTC, S1ngS1ng commented
Changes addressed in #21

2018-07-31 17:02 UTC, closed without merging