完成helmet第一小节翻译
FreeCodeCampChina/challenges pull request #4
Opened 2018-07-19 23:42 UTC by stanleyyylau

完成 helmet 第一小节翻译，请求合并，周末继续翻译

2018-07-20 00:26 UTC, S1ngS1ng requested changes
先谢谢你的翻译，请看一下我的 comments。

另外，如果你后续还打算继续添加翻译，本地继续弄，弄好了之后 `commit`，然后直接 `push` 到你 `fork` 里的这个 `branch` 就可以了。为什么要现在 `merge`？

2018-07-20 00:26 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/helmetjs.json
> +        "温馨提醒，这个项目是建立在下面这个模版之上的 <a href='https://glitch.com/#!/import/github/freeCodeCamp/boilerplate-infosec/'>Glitch模版地址</a>, 你也可以从 <a href='https://github.com/freeCodeCamp/boilerplate-infosec/'>Gi
请注意翻译后的显示效果：
![image](https://user-images.githubusercontent.com/13592559/42976304-b1f4acb2-8b75-11e8-95c1-0f783b46b557.png)

这样读起来就很不通顺了对吧？建议：
`注意，本项目在 <a href='https://glitch.com/#!/import/github/freeCodeCamp/boilerplate-infosec/'>这个 Glitch 项目</a> 的基础上进行开发。`
或者，`注意，本项目以 <a href='https://glitch.com/#!/import/github/freeCodeCamp/boilerplate-infosec/'>这个 Glitch 项目</a> 为基础。`

个人比较 prefer 第一种。
-------

顺便，请把 Glitch 链接之后的逗号换成全角的，并删除全角符号之后的空格。对比一下：
![image](https://user-images.githubusercontent.com/13592559/42976453-78183ba2-8b76-11e8-87dd-cb3a9f6ca006.png)

2018-07-20 00:26 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/helmetjs.json
> +        "黑客们可能会利用 Express/Node 的安全问题对你的网站做破坏如果他们知道你的网站是用 Express 搭建的. X-Powered-By: Express 默认情况下会被添加到所有响应的头部。不过 helmet.hidePoweredBy() 中间件可以帮你移除 X-Powered-By 头. 你甚至可以把头设置成其它的值。 如 app.use(helmet.hide
翻译时，请注意调整语序，中英文的语序习惯是不同的。
另外，**注意统一全角标点**！

建议：`如果黑客发现你的网站是用 Express 搭建的，那么他们就可以利用 Express 或 Node 现存的漏洞来攻击你的网站。`

@huluoyang @wudifeixue 这里，虽然原文没有，但我觉得给 `X-Powered-By: Express`，`helmet.hidePoweredBy()` 以及后面的 `app.use` 都加上 `<code></code>` 比较好。你们认为呢？

2018-07-20 00:56 UTC, huluoyang commented on 06-information-security-and-quality-assurance/helmetjs.json
> +        "黑客们可能会利用 Express/Node 的安全问题对你的网站做破坏如果他们知道你的网站是用 Express 搭建的. X-Powered-By: Express 默认情况下会被添加到所有响应的头部。不过 helmet.hidePoweredBy() 中间件可以帮你移除 X-Powered-By 头. 你甚至可以把头设置成其它的值。 如 app.use(helmet.hide
我觉得建议很不错，这个章节就是突出安全性的，所以隐藏 PoweredBy 是很有必要的。

2018-07-20 01:03 UTC, huluoyang commented
@S1ngS1ng 关于你的疑问：为什么要现在 merge？其实是提交 PR 就会自动显示 merge。
翻译指南中提倡任务分解，哪怕翻译完了一个章节的一个小节，我们也希望提交 PR 快速获得评注，如果 翻译 OK，我们应立即 Merge。这样 GitHub 才会给到翻译者一个 contribution的认可，也是一种鼓励。

2018-07-20 01:09 UTC, huluoyang commented on 06-information-security-and-quality-assurance/helmetjs.json
> +        "黑客们可能会利用 Express/Node 的安全问题对你的网站做破坏如果他们知道你的网站是用 Express 搭建的. X-Powered-By: Express 默认情况下会被添加到所有响应的头部。不过 helmet.hidePoweredBy() 中间件可以帮你移除 X-Powered-By 头. 你甚至可以把头设置成其它的值。 如 app.use(helmet.hide
@stanleyyylau  你要认真看翻译规范啊，中英文的语序习惯是完全不同的。

2018-07-20 05:12 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/helmetjs.json
> +        "黑客们可能会利用 Express/Node 的安全问题对你的网站做破坏如果他们知道你的网站是用 Express 搭建的. X-Powered-By: Express 默认情况下会被添加到所有响应的头部。不过 helmet.hidePoweredBy() 中间件可以帮你移除 X-Powered-By 头. 你甚至可以把头设置成其它的值。 如 app.use(helmet.hide
@huluoyang 

> 所以隐藏 PoweredBy 是很有必要的。

不会隐藏这个，加 `<code></code>` 的意思是改变显示的格式。

对比：
![image](https://user-images.githubusercontent.com/13592559/42984322-deb994e4-8ba0-11e8-9ed1-a44e9052a9d4.png)

2018-07-20 05:22 UTC, S1ngS1ng commented
@huluoyang 我的问题不是为什么会显示 merge 😂 我是问为什么要现在合并。

我明白任务分解的必要性。但我个人的理解是，分批的前提是不同的人 work on 不同的 part。对于一个人在同一个 task 上的 work，我比较建议提交的时候 `squash and merge`，这样我们最后的 commit history 不会那么乱。

但你说的 contribution 确实是 make sense 的。那就这么弄吧。我们需不需要新建一个 label，让大家可以标记 “Ready to review” 的 PR？

2018-07-20 12:19 UTC, stanleyyylau commented on 06-information-security-and-quality-assurance/helmetjs.json
> +        "黑客们可能会利用 Express/Node 的安全问题对你的网站做破坏如果他们知道你的网站是用 Express 搭建的. X-Powered-By: Express 默认情况下会被添加到所有响应的头部。不过 helmet.hidePoweredBy() 中间件可以帮你移除 X-Powered-By 头. 你甚至可以把头设置成其它的值。 如 app.use(helmet.hide
了解了，谢谢两位，后续会注意。

2018-07-22 05:25 UTC, stanleyyylau commented
完成前三小节翻译并修正之前的错误。

2018-07-22 19:34 UTC, S1ngS1ng commented
@stanleyyylau 请更新，fix 一下 conflicts

2018-07-23 01:43 UTC, stanleyyylau commented
求救，我不知道在这里怎么处理冲突。我之前只处理过本地合并的冲突，在 Pull Request 里面的冲突还是没处理过。我在网上找了些资料。

https://github.com/AgileVentures/MetPlus_PETS/wiki/Resolving-Pull-Request-merge-conflicts

但是我的 Upstream 是我 Clone 的 Repo，所以我 git pull origin translate 的时候没有显示有冲突。
咋办。求救。真的没办法了。

2018-07-23 02:46 UTC, huluoyang commented
我已在微信单独联系你。
这里说明一点：origin 才是你 clone 的仓库，upstream 是上游仓库，translate是 默认分支。
所以你 git pull origin translate == git pull 当然没有冲突。

2018-07-23 02:49 UTC, huluoyang commented
Conflicting files
`06-information-security-and-quality-assurance/helmetjs.json`
已经很清楚了，你应该先 git remote add upstream *** ，然后 git pull upstream translate，最后在 vim 界面退出。

2018-07-23 04:53 UTC, stanleyyylau commented
感谢，又学会一招。I believed it's ready to be merged now.

2018-07-23 17:22 UTC, S1ngS1ng requested changes
看下 comments。改好之后就可以 merge 了

个人建议：
`function` 翻译成“函数”，`method` 翻译成“方法”。
其中，“方法”是绑定在对象上的函数。
@huluoyang 如果你觉得合适，可以添加到 wiki

2018-07-23 17:22 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/information-security-with-helmetjs.json
> +        "如果黑客发现你的网站是用 Express 搭建的，那么他们就可以利用 Express 或 Node 现存的漏洞来攻击你的网站。<code>X-Powered-By: Express</code> 默认情况下会被添加到所有响应的头部。不过 helmet.hidePoweredBy() 中间件可以帮你移除 X-Powered-By 头. 你甚至可以把头设置成其它的值。 如 <cod
`移除 X-Powered-By 头. ` 标点！

--------
`设置成其它的值。 如` 去掉句号之后的空格。

2018-07-23 17:22 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/information-security-with-helmetjs.json
> +        "你的页面有可能会在未经你允许的情况下被放在 <frame> 或者 <iframe> 标签里面。其中一个风险就会导致 clickjacking 攻击。Clickjacking 这个小技巧可以在用户与网站 A 进行交互的时候，欺骗用户让用户以为他是在与网站 B 进行交互。通过 iframing 就可以恶意地执行你的页面。这种情况下，黑客可以在你的页面上再加一层隐藏的层。隐藏的按钮可
`你的页面有可能会在未经你允许的情况下被放在 <frame> 或者 <iframe> 标签里面。其中一个风险就会导致 clickjacking 攻击。` =>
`黑客可能会不经过你的允许，把你的页面嵌套在 <frame> 或者 <iframe> 标签里，用以实现“点击劫持”。`

`clickjacking` 有翻译的，参考：https://zh.wikipedia.org/wiki/%E7%82%B9%E5%87%BB%E5%8A%AB%E6%8C%81

------

`Clickjacking 这个小技巧可以在用户与网站 A 进行交互的时候，欺骗用户让用户以为他是在与网站 B 进行交互。` =>
`点击劫持是一种视觉上的欺骗手段，让用户误以为自己在与所看到的网页交互。`

这个叫“技巧”不合适吧。。 😂 

---------

`通过 iframing 就可以恶意地执行你的页面。这种情况下，黑客可以在你的页面上再加一层隐藏的层。隐藏的按钮可以用来执行恶意的脚本。` =>
`通过 iframe，黑客可以在你的页面上添加一个透明的“层”，然后把自己的恶意代码放在一个用户看不到的按钮中。这样一来，你的网站的执行环境就被黑客设置成了他想要的效果。`

1. “执行页面” 显然说不通
2. 不存在 `iframing` 这种技术，原文那样写是出于语法考虑
3. 我觉得 `隐藏` 可以换成 `看不见的`，因为这里强调的是用户看不到，而不是客观的“隐藏”

---------

`helmet 这个中间件可以设置 X-Frame-Options 这个头部。` 去掉“这个”

2018-07-23 17:22 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/information-security-with-helmetjs.json
> +        "我们不需要我们的应用被 iframe 引用。只需要 helmet.frameguard() 这个函数，然后传入配置对象  {action: 'deny'} 就可以了。"
`我们不需要我们的应用被 iframe 引用。` => 
`我们的应用不需要被 iframe 引用。`

-------

`只需要 helmet.frameguard() 这个函数，` =>
`你可以调用 <code>helmet.frameguard()</code> 这个方法，`

---------

`{action: 'deny'}` 也建议用 `<code>` 包起来

2018-07-23 17:22 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/information-security-with-helmetjs.json
> +          "text": "helmet.frameguard() 'action' 应该被设置成 'DENY'",
`helmet.frameguard() 'action' 应该被设置成 'DENY'` =>
`<code>helmet.frameguard()</code> 中的 <code>action</code> 属性的值应该为 'DENY'`

2018-07-23 17:22 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/information-security-with-helmetjs.json
>          "Cross-site scripting (XSS) is a frequent type of attack where malicious scripts are injected into vulnerable pages, with the purpose of stealing sensitive data like session cookies, or passw
这些剩下的部分重新开 PR 吧。现在的这个 PR 就先翻译到这儿，你觉得如何？

2018-07-24 01:40 UTC, stanleyyylau commented on 06-information-security-and-quality-assurance/information-security-with-helmetjs.json
>          "Cross-site scripting (XSS) is a frequent type of attack where malicious scripts are injected into vulnerable pages, with the purpose of stealing sensitive data like session cookies, or passw
嗯，可以。剩下的我翻译完再继续提 RP

2018-07-24 06:37 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/information-security-with-helmetjs.json
>          "Cross-site scripting (XSS) is a frequent type of attack where malicious scripts are injected into vulnerable pages, with the purpose of stealing sensitive data like session cookies, or passw
@stanleyyylau 好的。有空的话，先把这个 PR 里的更新了吧。谢谢

2018-07-24 07:08 UTC, stanleyyylau commented on 06-information-security-and-quality-assurance/information-security-with-helmetjs.json
>          "Cross-site scripting (XSS) is a frequent type of attack where malicious scripts are injected into vulnerable pages, with the purpose of stealing sensitive data like session cookies, or passw
我可能理解错你的意思了。你是指现在这个 PR 先合并，然后我继续翻译。把 ``helmet.js`` 全部翻译完了，然后另外再提 PR。是这个意思吗？我没太理解 “先把这个 PR 里的更新了吧” 具体是指？

2018-07-24 14:37 UTC, stanleyyylau commented on 06-information-security-and-quality-assurance/information-security-with-helmetjs.json
>          "Cross-site scripting (XSS) is a frequent type of attack where malicious scripts are injected into vulnerable pages, with the purpose of stealing sensitive data like session cookies, or passw
@S1ngS1ng  Never mind, I just saw your comments. Will update and let you know. @huluoyang Thanks for your edit, It reads much better now !

2018-07-24 14:40 UTC, stanleyyylau commented on 06-information-security-and-quality-assurance/information-security-with-helmetjs.json
> +        "你的页面有可能会在未经你允许的情况下被放在 <frame> 或者 <iframe> 标签里面。其中一个风险就会导致 clickjacking 攻击。Clickjacking 这个小技巧可以在用户与网站 A 进行交互的时候，欺骗用户让用户以为他是在与网站 B 进行交互。通过 iframing 就可以恶意地执行你的页面。这种情况下，黑客可以在你的页面上再加一层隐藏的层。隐藏的按钮可
You have my respect.

2018-07-24 17:25 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/information-security-with-helmetjs.json
>          "Cross-site scripting (XSS) is a frequent type of attack where malicious scripts are injected into vulnerable pages, with the purpose of stealing sensitive data like session cookies, or passw
@stanleyyylau 先按 comment 更新当前的翻译（如果你觉得有必要改的话，不过标点是真的要改）。
然后你可以本地创建个新的 branch 继续弄后续的翻译，后续的翻译开个新的 PR

2018-07-25 04:33 UTC, stanleyyylau commented on 06-information-security-and-quality-assurance/information-security-with-helmetjs.json
>          "Cross-site scripting (XSS) is a frequent type of attack where malicious scripts are injected into vulnerable pages, with the purpose of stealing sensitive data like session cookies, or passw
好，了解，thanks

2018-07-26 05:38 UTC, S1ngS1ng approved these changes

2018-07-28 08:48 UTC, huluoyang commented
🎉 恭喜霆霆成功完成第一个PR，Mission is impossible!

2018-07-28 08:48 UTC, merged