Translate responsive web design projects
FreeCodeCampChina/challenges pull request #42
Opened 2018-07-31 01:25 UTC by XERO75

2018-07-31 05:36 UTC, S1ngS1ng approved these changes
Thanks 👍

2018-08-01 04:36 UTC, S1ngS1ng requested changes

2018-08-01 04:36 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-projects.md
> +* 搭建产品着陆页
“着陆”？ 🤦‍♂️ 
“产品介绍页面” 或者 “产品主页” 就好。

2018-08-02 01:16 UTC, XERO75 commented on 01-responsive-web-design/responsive-web-design-projects.md
> +* 搭建产品着陆页
好的哈哈哈哈哈哈

2018-08-02 17:22 UTC, S1ngS1ng requested changes
统一一下标号方式，参考：https://github.com/FreeCodeCampChina/challenges/pull/39/files#diff-18bbc8e662f30c4c04c9f1e851e4d8f1

然后把 `<code>` 两边多余的的空格去掉。别的应该没啥问题了。麻烦你改下哈

2018-08-02 17:22 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-projects.json
> +        "<strong>需求13：</strong>导航栏应保持在视口的顶部。",
这一行和其他的标号方式不统一。
建议使用 `需求 13：` 这样的标号方式（注意空格！），更符合中文的表达习惯。`#13` 其实是英文的习惯，读作 “number 13”

2018-08-04 01:27 UTC, XERO75 commented on 01-responsive-web-design/responsive-web-design-projects.json
> +        "<strong>需求13：</strong>导航栏应保持在视口的顶部。",
get

2018-08-04 01:38 UTC, S1ngS1ng commented on 04-data-visualization/json-apis-and-ajax.md
> -
你的这个 file 不该改的吧，下次提交之前`checkout` 一下。
https://github.com/FreeCodeCampChina/challenges/blob/translate/CONTRIBUTING.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
看第三个问题
![image](https://user-images.githubusercontent.com/13592559/43671318-679b3ee6-974c-11e8-8446-9d1f55508c54.png)

2018-08-04 01:53 UTC, XERO75 commented on 04-data-visualization/json-apis-and-ajax.md
> -
呃呃，好的

2018-08-04 01:56 UTC, XERO75 commented on 04-data-visualization/json-apis-and-ajax.md
> -
git fetch upstream
git checkout upstream/translate -- the/path/to/that_file
这命令是在translate分支下执行的吗？另外那个the path to that file 是指哪个路径？

2018-08-04 04:08 UTC, S1ngS1ng commented on 04-data-visualization/json-apis-and-ajax.md
> -
@XERO75 在你现在的 branch 上执行就可以。
path to file 就是你要替换的文件路径啊。。你这里不小心改了 `04-data-visualization/json-apis-and-ajax.md`，那路径就是这个。

```
git checkout upstream/translate -- the/path/to/that_file
```

这个命令的意思就是，我要把本地的 `the/path/to/that_file` 文件替换成 upstream 上 translate 分支的 `the/path/to/that_file` 文件

然后执行一下 `git status` 你就能明白了

2018-08-07 11:33 UTC, XERO75 commented on 04-data-visualization/json-apis-and-ajax.md
> -
已经处理了，你看看

2018-08-07 17:15 UTC, S1ngS1ng commented on 04-data-visualization/json-apis-and-ajax.md
> -
@XERO75 
![image](https://user-images.githubusercontent.com/13592559/43791530-cab81d56-9a2a-11e8-8446-b79c8161cbfc.png)

没有处理好。晚上联系我，我远程帮你弄吧

2018-08-08 03:29 UTC, XERO75 commented on 04-data-visualization/json-apis-and-ajax.md
> -
好的微信加你了

2018-08-08 05:29 UTC, S1ngS1ng commented
Changes addressed in #74

2018-08-08 05:29 UTC, closed without merging