d3 1,2
FreeCodeCampChina/challenges pull request #43
Opened 2018-07-31 02:38 UTC by Mercy811

2018-08-01 10:07 UTC, huluoyang commented
可能是你第一次翻译英文吧，存在很多问题。
建议先去细看 wiki 中提到的翻译规范和翻译指南。

2018-08-01 10:07 UTC, huluoyang requested changes

2018-08-01 10:07 UTC, huluoyang commented on 04-data-visualization/data-visualization-with-d3.json
> +        "D3 提供了多种方法让你添加或改变你的文本中的元素。",
请先细读翻译规范，这句话明显啰嗦。
D3 有多种方法可以用来在文档中增加元素、修改元素。
这里的 your 是代词，不用翻译的。

2018-08-01 10:07 UTC, huluoyang commented on 04-data-visualization/data-visualization-with-d3.json
> +        "<code>select()</code> 从文本中选择一个元素。 他的参数是你想选择的元素的名字，返回一个 HTML 结点给文本中第一个和这个名字匹配的元素。下面是一个例子：",
document => 文档
It => 它
你看这样翻译会不会流畅点：
```
 <code>select()</code>  方法用来从文档从选择元素，它以你想查询的元素名称作为参数，返回第一个符合条件的 HTML 节点。
```

2018-08-01 10:07 UTC, huluoyang commented on 04-data-visualization/data-visualization-with-d3.json
> +        "<code>append()</code> 的参数是你想添加到文本中的的元素。 他给选择的元素添加一个HTML结点， 返回那个结点的句柄。",
的的 => 的
他 => 它
document => 文档
这一段请重新翻译，行文不流畅。

2018-08-01 10:07 UTC, huluoyang commented on 04-data-visualization/data-visualization-with-d3.json
> +        "<code>text()</text> 设置选中结点的文字内容或者得到当前的文字内容。 如果要设置文字内容，需要在圆括号中传入一个string类型的参数。",
method 总是自动忽略了，全局都有这个问题。
The <code>text()</code> method either sets the text of the selected node, or gets the current text.
<code>text()</code> 方法既可以给节点设置新的文本，也可以获取节点的当前文本。

2018-08-01 10:07 UTC, huluoyang commented on 04-data-visualization/data-visualization-with-d3.json
> +        "这里是一个例子。选择一个无序列表，添加列表项，添加文字：",
符号的使用很混乱

2018-08-01 10:07 UTC, huluoyang commented on 04-data-visualization/data-visualization-with-d3.json
> +        "像方法 <code>select()</code> 一样，<code>selectAll()</code> 也支持链式法则，你也可以用于其他方法。",
像 <code>select()</code> 方法一样

2018-08-01 10:07 UTC, huluoyang commented on 04-data-visualization/data-visualization-with-d3.json
> +       "<code>selectAll()</code> 方法选择一组元素。 它以 HTML 结点数组的形式返回该文本中所有匹配所输入字符串的对象。 这里是一个选择文本中所有锚标签的例子：",
行文不流畅，请重新翻译。

2018-08-07 02:17 UTC, Mercy811 commented on 04-data-visualization/data-visualization-with-d3.json
> +        "<code>append()</code> 的参数是你想添加到文本中的的元素。 他给选择的元素添加一个HTML结点， 返回那个结点的句柄。",
这样是否可行呢？
`上面这个例子找到页面上的第一个a标签（锚标签），将它作为一个HTML结点保存在变量<code>anchor</code>中。你也可以用其他的方法选择页面上的元素。例子中的 \"d3\" 是对 D3 对象的引用，可以通过它来访问 D3 的方法。`
`还可以用<code>append()</code> 和 <code>text()</code> 方法。`
`<code>append()</code>方法以你想添加到文档中的元素作为参数，给选中的元素添加一个HTML结点，返回那个结点的句柄。`
`<code>text()</text>方法既可以给节点设置新的文本，也可以获取节点的当前文本。 如果要设置文字内容，需要在圆括号中传入一个string类型的参数。`
`这里是一个选择无序列表、添加列表项和文字的例子：`

2018-08-07 02:27 UTC, Mercy811 commented on 04-data-visualization/data-visualization-with-d3.json
> +        "这里是一个例子。选择一个无序列表，添加列表项，添加文字：",
是指中英文混用还是符号使用位置不当呢？
除去<code>中的使用英文符号，其他全部使用中文符号。

2018-08-07 02:47 UTC, S1ngS1ng commented on 04-data-visualization/data-visualization-with-d3.json
> +        "<code>select()</code> 从文本中选择一个元素。 他的参数是你想选择的元素的名字，返回一个 HTML 结点给文本中第一个和这个名字匹配的元素。下面是一个例子：",
后面也加了很多空格。

2018-08-07 02:48 UTC, S1ngS1ng reviewed
@Mercy811 `<code>` 任何时候都不加空格。请先看一下 style-guide.md

2018-08-07 04:32 UTC, Mercy811 reviewed
修改了前两节的错误
新增了第三节

2018-08-08 17:26 UTC, S1ngS1ng requested changes
不要着急翻译后续的内容，请先把前面提到的问题处理完。记得前后要一致
注意，不要逐字逐句翻译，翻译完成之后记得读一遍。如果有不确定的，记得去官网做一下题目，明白了之后再翻译。

这个 PR 可以只翻译到这里，把提到的问题先处理好，后续的内容可以再开 PR

2018-08-08 17:26 UTC, S1ngS1ng commented on 04-data-visualization/data-visualization-with-d3.json
> +        "<code>select()</code>方法用来从文档中选择元素，它以你想查询的元素名称作为参数，返回第一个符合条件的HTML结点。这里是一个例子：",
请把多余的空格去掉

2018-08-08 17:26 UTC, S1ngS1ng commented on 04-data-visualization/data-visualization-with-d3.json
> +        "D3 有多种方法可以用来在文档中增加元素、修改元素",
结尾句号

2018-08-08 17:26 UTC, S1ngS1ng commented on 04-data-visualization/data-visualization-with-d3.json
> +        "上面这个例子找到页面上的第一个a标签（锚标签），将它作为一个HTML结点保存在变量<code>anchor</code>中。你也可以用其他的方法选择页面上的元素。例子中的 \"d3\" 是对 D3 对象的引用，可以通过它来访问 D3 的方法。",
全半角之间加空格。比如这里的 `a` 和 `HTML`。请仔细检查，后面还有

------

去掉结尾多余的空格

2018-08-08 17:26 UTC, S1ngS1ng commented on 04-data-visualization/data-visualization-with-d3.json
> +        "<code>text()</text>方法既可以给节点设置新的文本，也可以获取节点的当前文本。 如果要设置文字内容，需要在圆括号中传入一个 string（字符串）类型的参数。",
![image](https://user-images.githubusercontent.com/13592559/43852204-7b339040-9af1-11e8-9a0e-a9d498813481.png)
这里错了。

--------

句号之后多了空格

2018-08-08 17:26 UTC, S1ngS1ng commented on 04-data-visualization/data-visualization-with-d3.json
> +        ],
去掉额外的空格。下同

------

这一条是描述挑战内容的，可以适当地加一些导语，而且整体也应通顺一些：

`使用<code>select</code>方法选择文本中的<code>body</code>标签，然后用<code>append</code>方法为它添加一个<code>h1</code>标签，同时在<code>h1</code>中添加文本 \"Learning D3\"。`

2018-08-08 17:26 UTC, S1ngS1ng commented on 04-data-visualization/data-visualization-with-d3.json
> +       "<code>selectAll()</code>方法选择一组元素。它以 HTML 结点数组的形式返回该文本中所有匹配所输入字符串的对象。这里是一个选择文本中所有锚标签的例子：",
不要改原文的空格

------

`这里` => `以下`

2018-08-08 17:26 UTC, S1ngS1ng commented on 04-data-visualization/data-visualization-with-d3.json
> +        "像<code>select()</code>方法一样，<code>selectAll()</code>也支持链式法则，你也可以用其他方法。",
`链式法则` => `链式调用`

------

 `你也可以用其他方法。` => `你可以在它之后调用其他方法。`

2018-08-08 17:26 UTC, S1ngS1ng commented on 04-data-visualization/data-visualization-with-d3.json
> +       ],
空格

2018-08-08 17:26 UTC, S1ngS1ng commented on 04-data-visualization/data-visualization-with-d3.json
> +          "text": "页面上应该有3个<code>li</code>元素，每个元素的文本内容应为 \"list item\"。大小写和空格必须一致。",
`3` 两边要加空格

2018-08-08 17:26 UTC, S1ngS1ng commented on 04-data-visualization/data-visualization-with-d3.json
> +        "D3 的库是数据驱动的。可以使用 D3 的方法将数组形式的数据显示在页面上。",
`D3 的库是数据驱动的` =>

`D3 是数据驱动的`

或

`D3 是数据驱动的库`

2018-08-08 17:26 UTC, S1ngS1ng commented on 04-data-visualization/data-visualization-with-d3.json
> +        "常见的方法是在文档中为数据集中的每一个数据创建一个元素。D3 使用<code>enter()</code>方法",
`。D3 使用<code>enter()</code>方法` =>
`，为此，你可以使用 D3 的<code>enter()</code>方法。`

结尾句号

2018-08-08 17:26 UTC, S1ngS1ng commented on 04-data-visualization/data-visualization-with-d3.json
> +        "当<code>enter()</code>和<code>data()</code>方法连接使用时，它把从页面中选择的元素和数据集中的元素作比较。如果页面中选择的元素较少则创建缺少的元素。",
`当<code>enter()</code>和<code>data()</code>方法连接使用时` =>

`当<code>enter()</code>和<code>data()</code>方法一起使用时`

2018-08-08 17:26 UTC, S1ngS1ng commented on 04-data-visualization/data-visualization-with-d3.json
> +        "选择不存在的元素似乎有些难以理解。这段代码先选择页面上的<code>ul</code>元素，再选择所有的列表项，它将返回空。然后<code>data()</code>方法接收数组作为参数，并运行下面的代码三次，每次对应数组中的一个对象。<code>enter()</code>方法发现页面中没有<code>li</code>元素，但是需要 3 个（每个对应<code>datase
这句不是很通顺，建议对照题目重新翻译一下。不要逐字逐句地翻译

2018-08-08 17:26 UTC, S1ngS1ng commented on 04-data-visualization/data-visualization-with-d3.json
> +        "选择<code>body</code>结点，然后选择所有的<code>h2</code>元素。让 D3 为<code>dataset</code>数组中的每一个对象创建并添加文本为 \"New Title\" 的<code>h2</code>标签。你应该使用<code>data()</code>和<code>enter()</code>方法。"
`结点` => `节点`

2018-08-08 17:26 UTC, S1ngS1ng commented on 04-data-visualization/data-visualization-with-d3.json
> +        "在之前的挑战中，你为<code>dataset</code>数组中的每一个对象创建了一个新的<code>h2</code>元素，但是他们的文本都是相同的 \"New Title\"。 因为你还没有使用和每个<code>h2</code>元素关联的数据。",
多余的空格

2018-08-08 17:26 UTC, S1ngS1ng commented on 04-data-visualization/data-visualization-with-d3.json
> +        "改变<code>text()</code>方法那么每个<code>h2</code>元素显示<code>dataset</code>数组中的对应值加上一个空格和 \"USD\"。例如，第一个标题应该为 \"12 USD\"。"
`那么` => `使得`

2018-08-13 03:37 UTC, Mercy811 commented on 04-data-visualization/data-visualization-with-d3.json
> +        "<code>select()</code>方法用来从文档中选择元素，它以你想查询的元素名称作为参数，返回第一个符合条件的HTML结点。这里是一个例子：",
多余的空格是指 D3 吗？
我理解的格式说明应该是要加在两边加空格的吧 ![default](https://user-images.githubusercontent.com/31029607/44011781-1fa2b38c-9eed-11e8-8dc1-424ec097c4db.png)
标点符号都是用的全角

2018-08-13 03:42 UTC, Mercy811 commented on 04-data-visualization/data-visualization-with-d3.json
> +        "上面这个例子找到页面上的第一个a标签（锚标签），将它作为一个HTML结点保存在变量<code>anchor</code>中。你也可以用其他的方法选择页面上的元素。例子中的 \"d3\" 是对 D3 对象的引用，可以通过它来访问 D3 的方法。",
结尾没有空格的

2018-08-13 03:56 UTC, Mercy811 commented on 04-data-visualization/data-visualization-with-d3.json
> +       "<code>selectAll()</code>方法选择一组元素。它以 HTML 结点数组的形式返回该文本中所有匹配所输入字符串的对象。这里是一个选择文本中所有锚标签的例子：",
原文的空格是指的哪里呢？

2018-08-16 15:31 UTC, huluoyang requested changes

2018-08-16 15:31 UTC, huluoyang commented on 04-data-visualization/data-visualization-with-d3.json
> -        "Add an <code>attr()</code> method to set the \"fil
New item 的转义符号\ 不能丢，否则就会如上面红色一样的报错。

2018-08-16 15:31 UTC, huluoyang commented on 04-data-visualization/data-visualization-with-d3.json
> -        "Add an <code>attr()</code> method to set the \"fil
应该使用使用  重复出现

2018-08-16 15:31 UTC, huluoyang commented on 04-data-visualization/data-visualization-with-d3.json
> -        "Add an <code>attr()</code> method to set the \"fil
your code 这里的 code 应该不翻译。
`你应该使用<code>data()</code>方法。`

2018-08-16 15:31 UTC, huluoyang commented on 04-data-visualization/data-visualization-with-d3.json
> -        "Add an <code>attr()</code> method to set the \"fil
句号使用混乱

2018-08-16 15:31 UTC, huluoyang commented on 04-data-visualization/data-visualization-with-d3.json
> -        "Add an <code>attr()</code> method to set the \"fil
最后两个挑战涉及到使用D3的<code>data()</code>和<code>enter()</code>方法来动态展示数据。

2026-05-21 20:45 UTC, closed without merging