Advanced Node and Express Translation
FreeCodeCampChina/challenges pull request #45
Opened 2018-07-31 05:45 UTC by xiaoxizi333

2018-08-01 09:45 UTC, huluoyang requested changes

2018-08-01 09:45 UTC, huluoyang commented on 06-information-security-and-quality-assurance/advanced-node-and-express.json
> +      "title": "创建引擎模版",
set up =>设置   而不是创建

2018-08-01 09:45 UTC, huluoyang commented on 06-information-security-and-quality-assurance/advanced-node-and-express.json
> +        "提醒一下，这个项目建立在<a href='https://glitch.com/#!/import/github/freeCodeCamp/boilerplate-advancednode/'>Glitch</a>上的启动项目中，或是从<a href='https://github.com/freeCodeCamp/boilerplate-advancednode/'>GitH
或是从 => 也可以从

2018-08-01 09:45 UTC, huluoyang commented on 06-information-security-and-quality-assurance/advanced-node-and-express.json
> +        "你可以在应用程序的模版引擎中使用静态模板文件（如那些写在<em>Pug</em>里的）。在运行时，模版引擎会用服务端的真实值替换掉在模版文件中的变量，然后将模版转译成发送给客户端的 HTML 静态文件。这样可以更轻松地去构造 HTML 页面，在页面上不需要在客户端发送 API 请求去呈现变量。",
真实值 => 真实数据 
design an HTML page => 设计，而不是构造
allows for displaying of variables on the page without needing to make an API call from the client.
允许在页面直接显示变量内容而不需要发送 API 请求。

2018-08-01 09:45 UTC, huluoyang commented on 06-information-security-and-quality-assurance/advanced-node-and-express.json
> +        "最后, 你需要改变你对索引路由用页面路径<em>views/pug/index.pug</em>到<code>res.render</code>的请求的响应。",
行文不流畅，请重新翻译。

2018-08-01 09:45 UTC, huluoyang commented on 06-information-security-and-quality-assurance/advanced-node-and-express.json
> +        "如果一切就绪, 你需要刷新应用程序的主页，你可以看到 Pug 的成功建立的提示！你确定后就可以提交你的页面了。"
连续两个的 => 一个的

2018-08-01 09:46 UTC, huluoyang commented
万事开头难，慢慢来，1天翻译1个小节即可。

2018-08-02 02:43 UTC, xiaoxizi333 commented on 06-information-security-and-quality-assurance/advanced-node-and-express.json
> +        "你可以在应用程序的模版引擎中使用静态模板文件（如那些写在<em>Pug</em>里的）。在运行时，模版引擎会用服务端的真实值替换掉在模版文件中的变量，然后将模版转译成发送给客户端的 HTML 静态文件。这样可以更轻松地去构造 HTML 页面，在页面上不需要在客户端发送 API 请求去呈现变量。",
我觉得一般都是构造一个页面 而不是设计页面 我们是前端程序员 不是UI设计师 翻译应该要灵活一点 贴近自己做的事情才对，所以我觉得design an HTML page => 是构造而不是设计

2018-08-02 02:45 UTC, xiaoxizi333 commented on 06-information-security-and-quality-assurance/advanced-node-and-express.json
> +        "如果一切就绪, 你需要刷新应用程序的主页，你可以看到 Pug 的成功建立的提示！你确定后就可以提交你的页面了。"
What are talking about？

2018-08-02 17:40 UTC, S1ngS1ng requested changes
1. 看一下 style-guide，行内元素（如 `<a>`、`<em>` 之类的）是否加空格取决于内容
2. `to` 不能总是翻译成“去”，要根据上下文调整
3. `testString` 里 `assert` 的第二个参数（字符串）是要翻译的

2018-08-02 17:40 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/advanced-node-and-express.json
> +        "提醒一下，这个项目建立在<a href='https://glitch.com/#!/import/github/freeCodeCamp/boilerplate-advancednode/'>Glitch</a>上的启动项目中，也可以从<a href='https://github.com/freeCodeCamp/boilerplate-advancednode/'>Git
不必翻译成 `提醒一下`，翻译成 `注意` 就好

--------

`<a>` 标签加空格的方式请参考 style-guide，这里是要加的

2018-08-02 17:40 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/advanced-node-and-express.json
> +        "你可以在应用程序的模版引擎中使用静态模板文件（如那些写在<em>Pug</em>里的）。在运行时，模版引擎会用服务端的真实数据替换掉在模版文件中的变量，然后将模版转译成发送给客户端的 HTML 静态文件。这样可以更轻松地去构造 HTML 页面，允许在页面直接显示变量内容而不需要发送 API 请求。",
`app` 建议保留，可以不翻译

------

`更轻松地去构造` => `更轻松地构造`

2018-08-02 17:40 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/advanced-node-and-express.json
> +        "为了在 Node/Express 中运用模版引擎，你需要告诉你的 express <b>应用</b>去<b>建立</b>'pug'作为'view-engine' <code>app.set('view engine', 'pug')</code>",
`运用` => `适用`

-------

`你需要告诉你的 express <b>应用</b>去<b>建立</b>'pug'作为'view-engine' <code>app.set('view engine', 'pug')</code>` =>
`你需要在 express 中将 <b>app</b> 的 “view-engine” 设置为 “pug”，就像这样：<code>app.set('view engine', 'pug')</code>。`

1. 不要逐字逐句的翻译
2. 注意语序
3. 注意结尾句号
4. 注意标点。`<code>` 里面的不用改，但外面的要改

2018-08-02 17:40 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/advanced-node-and-express.json
> +        "最后, 你需要使用<code>res.render</code>方法去渲染<em>views/pug/index.pug</em>页面来作为路由请求的返回。",
这里的 `<em>` 两边需要加空格。

------

`去` => `来`

2018-08-02 17:40 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/advanced-node-and-express.json
> +        "如果一切就绪, 你需要刷新应用程序的主页，你可以看到 Pug 的成功建立的提示！你确定后就可以提交你的页面了。"
`如果一切就绪, 你需要刷新应用程序的主页，你可以看到 Pug 的成功建立的提示！你确定后就可以提交你的页面了。` =>
`如果一切顺利，刷新一下 app 的主页就可以看到 Pug 成功加载的提示，这时你就可以提交你的页面了。`

1. 这里不应该用半角标点
2. 注意调整一下表达方式

2018-08-02 17:40 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/advanced-node-and-express.json
> +            "getUserInput => $.get(getUserInput('url')+ '/_api/package.json') .then(data => { var packJson = JSON.parse(data); assert.property(packJson.dependencies, 'pug', 'Your project should list
这里，第二个参数（字符串）是要翻译的，和上面的 `text` 一样就好。

下同

2018-08-05 06:49 UTC, S1ngS1ng requested changes
别的没问题了

2018-08-05 06:49 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/advanced-node-and-express.json
> +            "getUserInput => $.get(getUserInput('url')+ '/') .then(data => { assert.match(data, /pug-variable(\"|')>Please login/gi, '项目的主页应用 pug 来呈现，但 .pug文件'); }, xhr => { throw new Error(xhr.statu
这里翻译的不太对。

`你的项目主页应使用 pug 作为渲染引擎，且 .pug 文件不应改变。`

2018-08-05 06:49 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/advanced-node-and-express.json
> +        "从服务器传递这些信息，你需要用变量和数据在 <em>res.render</em> 中添加一个对象作为第二论据。举一个例子，创建一个变量来传递对象： <code>{title: 'Hello', message: 'Please login'</code> 到你的主页",
code 两边的空格去掉

2018-08-05 06:49 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/advanced-node-and-express.json
> +        "在 Pug 文件中，你可以引用变量名来使用变量，像 <code>#{variable_name}</code> 插入元素中或像 <code>p= variable_name</code> 把元素与变量直接写在一起，这表示 p 元素的内容等价于这个变量。",
code 两边的空格去掉

2018-08-05 06:49 UTC, S1ngS1ng commented on 06-information-security-and-quality-assurance/advanced-node-and-express.json
> +            "getUserInput => $.get(getUserInput('url')+ '/') .then(data => { assert.match(data, /pug-success-message/gi, '项目的主页应用 pug 来呈现，但 .pug文件'); }, xhr => { throw new Error(xhr.statusText); })"
这里的翻译参考底下

2018-08-06 03:44 UTC, S1ngS1ng approved these changes
Thanks 👍

2018-08-07 06:33 UTC, merged