translate 2 lessons on ES6 chapter
FreeCodeCampChina/challenges pull request #6
Opened 2018-07-20 02:36 UTC by demongodYY

2018-07-20 02:36 UTC, demongodYY commented
先提交一下,看下中间有没有什么错误或不标准的地方好及时修改.

2018-07-20 03:55 UTC, huluoyang commented
全角符号和半角符号混用的问题，比较常见，望今后注意。

2018-07-20 03:56 UTC, ifyour commented
👌好的

Sent from my iPhone

On 20 Jul 2018, at 11:55, huluoyang <notifications@github.com<mailto:notifications@github.com>> wrote:


全角符号和半角符号混用的问题，比较常见，望今后注意。

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/FreeCodeCampChina/challenges/pull/6#issuecomment-406482046>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AOqkTCxyrEsDf6bdQv3pjYpYbqs36tMkks5uIVTKgaJpZM4VXXXj>.

2018-07-20 18:38 UTC, S1ngS1ng requested changes
1. 翻译中请使用全角标点，且全角标点之后不应由多余的空格
2. 如果 `<code></code>` 之后是中文字符，那应该添加空格；但如果是标点则不应添加
3. 记得加上代码示例中注释部分的翻译

@huluoyang @wudifeixue  建议所有的关键字都加上 `<code></code>` 你们觉得呢？

2018-07-20 18:38 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/es6.json
> +        "使用 <code>var</code> 关键字来声明变量,会出现重复声明导致变量被覆盖却不会报错的问题。",
请把逗号改成全角的。下同

--------

另外，这一行是引出下文的，建议结尾用冒号 `：`

2018-07-20 18:38 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/es6.json
>          "<blockquote>var camper = 'James';<br>var camper = 'David';<br>console.log(camper);<br>// logs 'David'</blockquote>",
这里的注释，也翻译下吧。下同

2018-07-20 18:38 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/es6.json
> +        "看上面的代码, <code>camper</code> 最初声明为 <code>James</code>,然后又被覆盖成了 <code>David</code>。",
原文 `As you can see in the code above`，这里的 `see` 不需要特意地翻译出来。
可以说 `在上面的代码中，` 或者 `上面的代码`

--------

标点问题也请修改一下

--------

建议这里不用“最初声明为”，改用“初始值为”

---------

既然是字符串，个人建议这里写成 `<code>'James'</code>` 和 `<code>'David'</code>`
效果图：
![image](https://user-images.githubusercontent.com/13592559/43015794-633ebeb0-8c05-11e8-8492-0b4442661a59.png)

2018-07-20 18:38 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/es6.json
> +        "在小型的应用中,你可能不会遇到这样的问题,但是当你的代码规模变得更加庞大的时候,就可能会在你不经意的时候产生变量的覆盖",
`就可能会在你不经意的时候产生变量的覆盖` 建议改成：
`就可能会在不经意间覆盖了之前定义的变量。`

注意结尾的句号

2018-07-20 18:38 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/es6.json
> +        "因为这样的行为并不会报错，导致 debug 变得更加困难。<br>",
两种说法：
1. `这样的行为不会报错导致了 debug 非常困难。`
2. `因为这样的行为不会报错，所以当它出现时，debug 会非常困难。`

你来决定吧

2018-07-20 18:38 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/es6.json
> +        "在 ES6 中使用了新的关键字 <code>let</code> 来解决 <code>var</code> 关键字可能带来的问题。",
`在 ES6 中使用了新的关键字` 建议改成：
`ES6 引入了新的关键字`

--------

`可能带来的问题。` 建议改成：
`带来的潜在问题。`

`potential` 不是修饰 `带来`，而应该修饰 `issue`。因为 `带来` 已经实锤了，上面就证明过了

2018-07-20 18:38 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/es6.json
> +        "如果你在上面的代码中，使用了 <code>let</code> 关键字来代替 <code>var</code>关键字,结果会是一个报错。",
`<code>var</code>` 之后应该有一个空格。

-----------

`an error` 也不必翻译成 `一个报错`，这里的 `an` 是泛指。

建议：

`如果你在上面的代码中用 <code>let</code> 代替 <code>var</code> 关键字，那么就会出现报错。`

2018-07-20 18:38 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/es6.json
> +        "可以在可以在浏览器的控制台里看见这个错误。",
`可以在可以在浏览器的控制台里看见这个错误。` =>
`你可以在浏览器的控制台里看见这个错误。`

2018-07-20 18:38 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/es6.json
> +          "text": "<code>catName</code> 变量的值应该为 <code>Oliver</code>。",
统一一下。既然底下你加上了引号，这里就也加上吧

2018-07-20 18:38 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/es6.json
> +        "<code>let</code> 关键字的作用类似,但会有一些额外的特性。 当你使用 <code>let</code> 关键字在代码块,语句或者表达式里声明变量的时候,这个变量的作用域就在当前的代码块,语句或表达式之中。",
请去掉全角句号后多余的空格

---------

注意语序

`当你使用 <code>let</code> 关键字在代码块,语句或者表达式里声明变量的时候,` => `如果你在代码块、语句或表达式中使用关键字 <code>let</code> 声明变量，`

---------

`就在` => `就被限制在`

2018-07-20 18:38 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/es6.json
>          "<blockquote>var numArray = [];<br>for (var i = 0; i < 3; i++) {<br>&nbsp;&nbsp;numArray.push(i);<br>}<br>console.log(numArray);<br>// returns [0, 1, 2]<br>console.log(i);<br>// returns 3</bl
这里的注释也记得加上翻译哈。下同

2018-07-20 18:38 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/es6.json
> +        "这个行为在你一个创建函数用来存储在 for 循环中使用的 <code>i</code> 变量的时候,会出现问题。这是因为函数存储的值会因为全局变量 <code>i</code>的变化而不断的改变。",
`如果你在 <code>for</code> 循环中创建了使用 <code>i</code> 变量的函数，那么在后续调用函数的时候，上面提到的这种行为就会导致问题。`

2018-07-20 18:38 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/es6.json
> +        "可以看到, <code>printNumTwo()</code> 打印了 3 而不是 2。 这是因为 <code>i</code> 发生了改变,并且函数 <code>printNumTwo()</code> 返回的是全局变量 <code>i</code>的值,而不是 for 循环中创建函数时 <code>i</code> 的值。The <code>let</code> 关键字就
迷之 `The` 😂 

-------

这里的结尾应该用全角冒号`：`

2018-07-20 18:38 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/es6.json
> +        "<code>i</code> 在全局作用域中没有声明,所以它没有被定义, 它只会在 for 循环的语句中被声明。 因为在循环语句中的 <code>let</code>关键字创建了拥有独一无二的值 (0, 1, 或 2) 的三个不同 <code>i</code> 变量,所以 <code>printNumTwo()</code> 返回了正确的值。",
建议在不影响意思的前提下，尽量调整为主动语态。 @huluoyang 

`它只会在 <code>for</code> 循环的语句中被声明` => `它的声明只会发生在 <code>for</code> 循环内。`

-----------

`因为在循环语句中的 <code>let</code>关键字创建了拥有独一无二的值 (0, 1, 或 2) 的三个不同 <code>i</code> 变量` 建议改成：
`在循环执行的时候，<code>let</code> 关键字创建了三个不同的 <code>i</code> 变量，他们的值分别为 0、1 和 2`

个人觉得这里补充说明一下可能会更好

2018-07-20 18:38 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/es6.json
> +        "这个练习说明了使用 <code>var</code> 与 <code>let</code>关键字声明变量时,作用域之间的不同。当编写类似这个练习中的函数的时候,通常来说最好还是使用不同的变量名,用于避免困惑。"
`使用不同的变量名,用于避免困惑。` 建议改成：
`使用不同的变量名来避免误会。`

2018-07-20 18:38 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/es6.json
> +          "text": "在 if 语句中声明的 <code>i</code> 变量的值是 \"block scope\"。",
`在 if 语句中声明的 <code>i</code> 变量的值是 \"block scope\"。` 建议改成：
`在 <code>if</code> 语句中声明的 <code>i</code> 变量的值应为 \"block scope\"。`

2018-07-20 18:38 UTC, S1ngS1ng commented on 02-javascript-algorithms-and-data-structures/es6.json
> +          "text": "<code>checkScope()</code> 应当 返回 \"function scope\"",
请去掉多余的空格

2018-07-22 05:34 UTC, demongodYY commented on 02-javascript-algorithms-and-data-structures/es6.json
>          "<blockquote>var camper = 'James';<br>var camper = 'David';<br>console.log(camper);<br>// logs 'David'</blockquote>",
请问是所有 desc ，test, files 的代码块里的注释都需要翻译吗？因为看到很多类似 \\use strict 这一类的注释？

2018-07-25 02:29 UTC, demongodYY commented
请问是所有 desc ，test, files 的代码块里的注释都需要翻译吗？因为看到很多类似 \use strict 这一类的注释？ @S1ngS1ng @huluoyang

2018-07-25 04:35 UTC, S1ngS1ng commented
@demongodYY `desc`、`tests` 的肯定要。`files` 里面翻译注释的部分，如果注释对做题是有帮助的。
`use strict;` 是 JS 关键字。https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

2018-07-29 13:36 UTC, demongodYY commented
@huluoyang md文件在哪里呀？

2018-07-29 16:10 UTC, S1ngS1ng commented
@demongodYY 你需要 `pull --rebase` 一下。你的 branch 没有更新。。

https://github.com/demongodYY/challenges/tree/translate/02-javascript-algorithms-and-data-structures

https://github.com/FreeCodeCampChina/challenges/tree/translate/02-javascript-algorithms-and-data-structures

2018-07-30 06:13 UTC, S1ngS1ng commented
@demongodYY 你这个 file change 太多啦。。考虑重开个 branch 吧，只保留你自己改过的 files　

2018-07-30 06:21 UTC, wudifeixue commented
建议所有的关键字都加上`<code></code>`这个我不觉得是好事儿，这个一定要根据题来决定，我和我弟正在刷题能看到很多问题，但是关键字都加上`<code></code>`可以肯定不是好的选择。

2018-07-30 09:21 UTC, demongodYY commented
@S1ngS1ng 所以是要重新提个 PR 吗？ T_T

2018-07-30 18:08 UTC, S1ngS1ng commented
@demongodYY 可以的，不会很麻烦。
```bash
# 获取 upstream 的 HEAD 指针
git fetch upstream

# 基于 upstream 的 translate branch 新建一个 branch
git checkout -b translate-es6 upstream/translate

# 由于你这个 PR 是基于你的 translate branch 开的，
# 所以把这个 branch 上属于你的文件改动应用到新的 branch 上
git checkout translate -- 02-javascript-algorithms-and-data-structures/es6.json
git checkout translate -- 02-javascript-algorithms-and-data-structures/es6.md

# 这个应该只输出你改过的两个文件才对
git status

# add、commit、push
git add .
git commit -m "Finish translation of ES6"
git push origin translate-es6

# 然后用这个新的 branch 再开 PR 就好了
```　

2018-07-30 21:20 UTC, S1ngS1ng commented
@demongodYY 请参考 [常见问题](https://github.com/FreeCodeCampChina/challenges/blob/60ed482767dac448fc3be329dcb96ddcc7aba749/CONTRIBUTING.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) 的最后一条

2018-08-01 16:09 UTC, S1ngS1ng commented
Changes addressed in #51

2018-08-01 16:09 UTC, closed without merging