translate Responsive Web Design Principles -100%
FreeCodeCampChina/challenges pull request #7
Opened 2018-07-20 06:36 UTC by rainpure

2018-07-22 23:01 UTC, S1ngS1ng requested changes
注意标点，整体上问题不大 👍 

想问你下，对于原文：“Here's an example of a media query that returns the content when the device's width is less than or equal to 100px:” 这句话的 `rerturns the content`，你是如何理解的？你认为它里面的 `content` 是代表什么？

2018-07-22 23:01 UTC, S1ngS1ng commented on .vscode-upload.json
> +}]
请把这个文件删掉。不需要提交。可以使用命令 `git rm .vscode-upload.json`，然后 `commit` `push`

2018-07-22 23:01 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "下面是一个媒体查询的例子：当设备宽度小于或等于 100px 时返回内容",
`下面是一个媒体查询的例子：当设备宽度小于或等于 100px 时返回内容` =>

`下面是一个媒体查询的例子，当设备宽度小于或等于 100px 时返回内容：`

翻译的意思是对的，注意标点的使用

2018-07-22 23:01 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "以下媒体查询当设备高度大于或等于 350px 时返回内容:",
`以下媒体查询当设备高度大于或等于 350px 时返回内容:` =>
`以下定义的媒体查询，是当设备高度大于或等于 350px 时返回内容：`

注意通顺性，和标点

2018-07-22 23:01 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "媒体查询由媒体类型组成，如果媒体类型与展示文档的设备类型匹配，则应用对应的样式。你可以在你的媒体查询中用上你想用的选择器和样式。",
`文档` 建议 => `网页`

2018-07-22 23:01 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-principles.json
> +          "testString": "assert(code.match(/@media\\s?\\(max-height:\\s*?800px\\)/g), '给 <code>height</code> 小于或等于 800px 的设备声明一个 <code>@media</code> 查询');"
`给 <code>height</code> 小于或等于 800px 的设备声明一个 <code>@media</code> 查询` =>

`使用 <code>@media</code> 为 <code>height</code> 小于或等于 800px 的设备添加一个媒体查询。`

注意句号。
两行同步更新

2018-07-22 23:01 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "用 CSS 来做图片自适应其实很简单。除了在元素上使用绝对宽度外:",
结尾应该是全角分号：

2018-07-22 23:01 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "<code>max-width</code> 属性能让图片以 100% 的最大宽度适应其父容器的宽度，但图片不会拉伸得比原始宽度还宽。将 <code>display</code> 属性设置为 block 将 image 标签从内联元素（默认值）更改为行内块级元素。设置 <code>height</code> 属性为 auto 保持图片的原始宽高比",
`将 <code>display</code> 属性设置为 block 将 image 标签从内联元素（默认值）更改为行内块级元素。` =>

`将 <code>display</code> 属性设置为 <code>block</code> 可以让 image 标签从内联元素（默认值）更改为行内块级元素。`

2018-07-22 23:01 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-principles.json
> +          "testString": "assert(code.match(/max-width:\\s*?100%;/g), '你的 <code>img</code> 标签应该包含 <code>max-width</code> 为 100% 的样式。');"
这里与上一行相同就好啦。上面翻译的很好

2018-07-22 23:01 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "使图片出现 \"retina\" （优化在高分辨率设备下的展示）最简单的方式是定义它们的 <code>width</code> 和 <code>height</code> 值为源文件宽高的一半。",
括号前不应该有空格。

--------

注意，这里的 “appear” 翻译成 “出现” 可能会比较奇怪。
之所以这里的 “retina” 加了引号，是因为 “retina” 本身是 “视网膜” 的意思，但 Apple 公司通过 Retina Display 把这个词弄火了。根据后文，不难猜出这里的 “retina” 指的是 Retina Display 那个技术，或者说是那种表现。所以 “appear” 肯定不能翻译成 “出现”。

所以我们这里不如就这样意译：
`为优化图片在高分辨率设备下的显示效果，最简单的方式是……`

2018-07-22 23:01 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "<blockquote>&lt;style&gt;<br>&nbsp;&nbsp;img { height: 250px; width: 250px; }<br>&lt;/style&gt;<br>&lt;img src=&quot;coolPic500x500&quot; alt=&quot;一个更高质的图片&quot;&gt;</blockquote>",
`一个更高质的图片` => `一张高质量的图片`

2018-07-22 23:01 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-principles.json
> +          "text": "你的 <code>img</code> 标签应含有 100 像素的 <code>width</code>。",
`你的 <code>img</code> 标签应含有 100 像素的 <code>width</code>。` 建议 =>

`你的 <code>img</code> 标签的 <code>width</code> 应为 100 像素。`

或：

`你的 <code>img</code> 标签的 <code>width</code> 值应为 100px。`

考虑到原文，应该采用第一种，不过为了整体统一，个人推荐第二种。

你来决定吧。下同

2018-07-22 23:01 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "除了用 <code>em</code> 或 <code>px</code> 去设置文本大小, 你还可以用视窗单位来控制排版。视窗单位，如百分比，是相对单位，但它们基于不同的元素。视口单元相对于设备的视口尺寸 (宽度或高度) ，百分比是相对于父级元素的大小。",
应改使用全角括号

------

https://developer.mozilla.org/zh-CN/docs/Web/CSS/length

![image](https://user-images.githubusercontent.com/13592559/43050969-4208c084-8dc6-11e8-9074-5bb754ca7aa8.png)


统一成“视口”吧。（哎我觉得这个名字好奇怪 🤦‍♂️ 

下同

2018-07-22 23:01 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "<ul><li><code>vw: 10vw</code> 视窗宽度的 10%。</li><li><code>vh: 3vh</code> 视窗高度的 3%。</li><li><code>vmin: 70vmin</code> 视窗中较小纬度的 70%  (高度 vs. 宽度).</li><li><code>vmax: 100vmax</code> 视窗中较大纬度的 100%
`<li><code>vw: 10vw</code> 视窗宽度的 10%。</li>` 建议 =>
`<li><code>vw</code>：如 <code>10vw</code> 的意思是视窗宽度的 10%。</li>`

建议每个 `li` 都这样修改下

Before：
![image](https://user-images.githubusercontent.com/13592559/43051006-ec9c88be-8dc6-11e8-8327-faab5131977f.png)

After：

![image](https://user-images.githubusercontent.com/13592559/43051035-4d1ab3d2-8dc7-11e8-97fa-3261a597e828.png)

--------

`视窗中较小纬度的 70% (高度 vs. 宽度)` => 
`视窗高度/宽度较小值的 70%。`
或
`视窗高度和宽度中较小值的 70%。`

顺便，`较大` 那个也改下。“纬度” 不是很 make sense。“维度” 好像也不太对。
符号也要注意，结尾是句号，括号应该是全角

2018-07-22 23:01 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "设置 <code>h2</code> 标签 <code>width</code> 为视窗宽度的 80%，并且段落 <code>width</code> 为小尺寸视窗的 75%。"
`小尺寸视窗的 75%。` => `视窗高度和宽度中较小值的 70%`

2018-07-23 14:13 UTC, rainpure commented on .vscode-upload.json
> +}]
`content` 我的理解是 “网页内容”

2018-07-23 19:01 UTC, huluoyang requested changes

2018-07-23 19:01 UTC, huluoyang commented on 01-responsive-web-design/responsive-web-design-principles.json
> +          "text": "你的 <code>h2</code> 标签 <code>width</code> 应为 80vw。",
这里的`你的`，是代词，可以省略，其他地方同理。

2018-07-23 19:01 UTC, huluoyang commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "除了用 <code>em</code> 或 <code>px</code> 去设置文本大小, 你还可以用视窗单位来控制排版。视窗单位，如百分比，是相对单位，但它们基于不同的元素。视口单元相对于设备的视口尺寸 (宽度或高度) ，百分比是相对于父级元素的大小。",
`Viewport units` 的翻译前面是视窗单位，后面是视口单元，不一致，以前者为准。

2018-07-23 19:01 UTC, huluoyang commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "<code>max-width</code> 属性能让图片以 100% 的最大宽度适应其父容器的宽度，但图片不会拉伸得比原始宽度还宽。将 <code>display</code> 属性设置为 block 将 image 标签从内联元素（默认值）更改为行内块级元素。设置 <code>height</code> 属性为 auto 保持图片的原始宽高比",
`display:block` 对应的是块级元素
`display:inline-block` 对应的才是行内块级元素

2018-07-23 19:01 UTC, huluoyang commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "媒体查询是 CSS3 中针对不同可视窗口大小定义不同样式的新技术，可视窗口是用户在网页上的可见区域，根据访问网站的设备不同而不同。",
媒体查询是 CSS3 中引入的一项新技术，它可以根据不同的可视窗口大小显示不同的布局。

2018-07-23 19:01 UTC, huluoyang commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "<ul><li><code>vw: 10vw</code> 视窗宽度的 10%。</li><li><code>vh: 3vh</code> 视窗高度的 3%。</li><li><code>vmin: 70vmin</code> 视窗中较小纬度的 70%  (高度 vs. 宽度).</li><li><code>vmax: 100vmax</code> 视窗中较大纬度的 100%
dimension 在此处是尺寸的意思，和维度无关。
<li><code>vmin: 70vmin</code> 视窗中较小尺寸的 70%  (高度 VS 宽度)。</li>
<li><code>vmax: 100vmax</code> 视窗中较大尺寸的 100%  (高度 VS 宽度)。</li>

height vs. width 的正确翻译应该是：高度 VS 宽度，英文的 vs 要变成大写：VS，便于文字高度保持统一。

2018-07-23 19:01 UTC, huluoyang commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "<code>max-width</code> 属性能让图片以 100% 的最大宽度适应其父容器的宽度，但图片不会拉伸得比原始宽度还宽。将 <code>display</code> 属性设置为 block 将 image 标签从内联元素（默认值）更改为行内块级元素。设置 <code>height</code> 属性为 auto 保持图片的原始宽高比",
这个地方的翻译不对，应统一为：
`将 <code>display</code> 属性设置为 <code>block</code> 可以让 image 标签从内联元素（默认值）更改为块级元素。`

2018-07-23 19:01 UTC, huluoyang commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "除了用 <code>em</code> 或 <code>px</code> 去设置文本大小, 你还可以用视窗单位来控制排版。视窗单位，如百分比，是相对单位，但它们基于不同的元素。视口单元相对于设备的视口尺寸 (宽度或高度) ，百分比是相对于父级元素的大小。",
我觉得在这点上，不能遵从 MDN 的翻译。

viewport => 视口（视图 + 端口 = 视口，这纯粹是字面翻译）
viewport => 视窗（视图 + 窗口 = 视窗，指可以看到的窗口）

我稍后会把常用名字翻译总结出来。

2018-07-24 06:46 UTC, S1ngS1ng commented on .vscode-upload.json
> +}]
@rainpure 那天没想明白，现在想明白了，意思应该是“css 的内容”，就是后面大括号里定义的 css 规则。
当设备宽度小于或等于 100px 时，返回（括号里定义的 CSS ）内容。

你考虑下，如何翻译合适吧 😄

2018-07-24 06:48 UTC, S1ngS1ng requested changes
其他部分没问题了。那句话你考虑下吧，通顺就 OK 哈

2018-07-24 06:48 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "<code>max-width</code> 属性能让图片以 100% 的最大宽度适应其父容器的宽度，但图片不会拉伸得比原始宽度还宽。将 <code>display</code> 属性设置为 <code>block</code> 可以让 image 标签从内联元素（默认值）更改为行内块级元素。设置 <code>height</code> 属性为 auto 保持图片的原始宽高比"
结尾句号

2018-07-25 10:21 UTC, huluoyang requested changes

2018-07-25 10:21 UTC, huluoyang commented on 01-responsive-web-design/responsive-web-design-principles.md
> +设置字体自适应
Typography => 排版

2018-07-25 10:21 UTC, huluoyang commented on 01-responsive-web-design/responsive-web-design-principles.md
> +如今，从大屏的台式电脑到小屏的手机，我们有各式各样的设备可以上网。这些设备有着不同的屏幕尺寸、分辨率和处理能力。响应式网页设计是一种对内容应用不同约束条件的设计方法，能使页面结构和 CSS 规则能够灵活应用于不同设备之间的差异。一般来说，页面的 CSS 是设计给目标用户看的。如果你希望大部分流量来自移动端用户，采取“移动端优先”的设计方法，然后再为大屏幕添加展示规则。如果你的访客来自桌面用户，则
Responsive Web Design => 响应式 Web 设计
Responsive Web Design is an approach to designing web content that responds to the constraints of different devices. 
响应式 Web 设计是一种能自如响应不同尺寸设备的设计方法。（不要按字面意思翻译）
If you expect most of your traffic to be from mobile users, take a 'mobile-first' approach. Then add conditional rules for larger screen sizes.
expect => 预计、期望
hope => 希望。
如果你预计网站的大部分流量来自移动端，那么应该采取“移动端优先“的策略，再为 PC 端做兼容。

2018-07-25 10:54 UTC, huluoyang requested changes

2018-07-25 10:54 UTC, huluoyang commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "用 CSS 来做图片自适应其实很简单。除了在元素上使用绝对宽度外：",
用 CSS 来让图片自适应其实很简单。不要使用绝对单位：

2018-07-25 10:54 UTC, huluoyang commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "你还可以这样用：",
你应该使用：

2018-07-25 10:54 UTC, huluoyang commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "这是一个图片宽高设置为源文件宽高一半的例子：",
这是一个图片宽高设置为源文件一半的例子：

2018-07-25 10:54 UTC, huluoyang commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "设置 <code>h2</code> 标签 <code>width</code> 为视口宽度的 80%，并且段落 <code>width</code> 为视口高度和宽度中较小值的 70%。"
viewport  统一翻译为视窗，而不是视口，此处要全局修改。
vmin和 vmax 对应的翻译中都丢掉了视窗，应该是视窗高度/宽度。

2018-07-25 10:54 UTC, huluoyang commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "除了用 <code>em</code> 或 <code>px</code> 去设置文本大小, 你还可以用视口单位来控制排版。视口单位，如百分比，是相对单位，但它们基于不同的元素。视口单元相对于设备的视口尺寸 (宽度或高度) ，百分比是相对于父级元素的大小。",
responsive typography  响应式排版
Viewport units, like percentages, are relative units, but they are based off different items.
视窗单位还有百分比，它们都是相对单位，但却基于不同的参照物。

在你的翻译中对于 Viewport units 的翻译不统一，一会是视窗单位，一会是视窗单元，请修正。

2018-07-26 05:40 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-principles.json
> +        "<code>max-width</code> 属性能让图片以 100% 的最大宽度适应其父容器的宽度，但图片不会拉伸得比原始宽度还宽。将 <code>display</code> 属性设置为 <code>block</code> 可以让 image 标签从内联元素（默认值）更改为块级元素。。设置 <code>height</code> 属性为 auto 保持图片的原始宽高比。"
`更改为块级元素。。设置 `

这里多了个句号。。

2018-07-26 05:41 UTC, S1ngS1ng commented on 01-responsive-web-design/responsive-web-design-principles.json
> +          "testString": "assert($('img').css('height') == '100px', '<code>img</code> 标签应含有 100 像素的 <code>height</code>。');"
顺便，这里也改下吧，`100px`

2018-07-26 05:42 UTC, S1ngS1ng approved these changes

2018-07-26 05:43 UTC, S1ngS1ng commented
@rainpure 先 approve 了。记得改下，小问题

2018-07-27 05:26 UTC, S1ngS1ng commented
Perfect :shipit:

2018-07-28 09:46 UTC, huluoyang commented
在#35的 PR 中已成功 merge，所以此 PR 应 close。

2018-07-28 09:46 UTC, closed without merging