translate html chapter to 40%
FreeCodeCampChina/challenges pull request #9
Opened 2018-07-21 02:32 UTC by huluoyang

以后争取每天更新 10%，剩余部分在一周内更新完成。

2018-07-21 06:50 UTC, S1ngS1ng requested changes
关于字符串。我觉得这一篇不涉及 JavaScript，所有的字符串都可以用 `<code></code>` 包裹起来，可以表示这些部分与其他部分（描述性文字）是不同的

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "欢迎来到 FreeCodeCamp 的 HTML 编码挑战，这些挑战将会帮助你逐步掌握 web 开发。",
标准拼写是 `freeCodeCamp`。
![image](https://user-images.githubusercontent.com/13592559/43032279-ff2df720-8c67-11e8-9c0e-1041275ecbe9.png)

---------

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "HTML 是英文 Hyper Text Markup Language(超文本标记语言)的缩写。首先，使用 HTML 来制作一个简单的网页，你可以直接在本网页内置的代码编辑器中编辑代码。"
这个仿佛咱们之前讨论过，印象中应该是中文括号
`HTML 是英文 Hyper Text Markup Language(超文本标记语言)的缩写`
VS:
`HTML 是英文 Hyper Text Markup Language（超文本标记语言）的缩写`

我比较 prefer 后者。

至少现在这样，如果你打算用半角的，也得加空格

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "你看到代码编辑器中的 <code>&#60;h1&#62;Hello&#60;/h1&#62;</code> 了吗? 那就是一个 HTML 标签，<code>h1</code> 是 <code>header1</code> 的简写，意思是主标题。",
`h1` 不是代表 `header1`，而是 `heading level 1`，或者 `level 1 heading`。参考：https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements

而 `header` 就是另一个标签了：https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header

下同

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "任务：请更改主标题的内容为：Hello World。"
`任务：请更改主标题的内容为：Hello World。` => 
`任务：请把主标题的内容改为 <code>Hello World</code>。`

或者保留 `h1`：
`任务：请把 <code>h1</code> 标签里的内容改为 <code>Hello World</code>。`

会不会好些？感觉一句话两个冒号很奇怪= =下同

![image](https://user-images.githubusercontent.com/13592559/43032409-f789b2e0-8c6a-11e8-8f47-b7efb63f2831.png)

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "Web开发者通常用 <a href='http://www.ruanyifeng.com/blog/2009/04/lorem_ipsum.html'>lorem ipsum text</a> 来做占位符，占位符就是占着位置的一些文字，没有实际意义。",
Web 后应该有空格。不过这里的 Web 你觉得需要保留么？

给 wikipedia 的链接，会不会比给个人博客的链接好些？或者不给也可以，毕竟后文也有解释，把这个链接放到地下作为来源就好。

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "从公元16世纪开始<code>lorem ipsum text</code>就被当做占位符了，这种传统延续到了互联网时代。于此同时，孙悟空也在五指山下压了500年，然后就进化成程序猿了，是不是很巧合，哈哈。",
这里的 code block 前后也要加空格。

-----------

~~`是不是很巧合，哈哈。`~~ 。。。删了吧 ！😂 前面的内容用于引出下文我觉得还 ok，不过我觉得还是不要带入个人的感情色彩
　

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "注释是用来给代码添加一些说明，方便团队合作或日后自己查看，但又不影响代码本身。",
`注释是用来给代码添加一些说明，方便团队合作或日后自己查看，但又不影响代码本身。` 建议：

`注释的作用是给代码添加说明，方便团队合作或日后自己查看，但又不影响代码本身。`
或者
`注释是用来给代码添加说明，但又不影响代码本身的一种方式。它可以为团队合作提供便利，也可以用于日后自己查看。`

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "记住：注释的开始标记是 <code>&#60;!--</code>，结束标记是 <code>--></code>。",
这里用 `>` 可以的么？感觉还是用 HTML entity 靠谱

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "任务：主标题和段落都注释掉，副标题留着。"
`副标题留着。` => `保留副标题。`

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "HTML5 引入了很多更具描述性的 HTML 标记，例如：<code>header</code>、<code>footer</code>、<code>nav</code>、<code>video</code>、<code>article</code>、<code>section</code> 等等。",
`标记` => `标签`

**下同！** 全局搜索一下吧，底下还有很多

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "这些标记让 HTML 更易读，同时对搜索引擎优化和可访问性更友好。",
Accessibility 字面意思确实是“可访问性”。不过 wikipedia 和 MDN 给出的都是 “无障碍”

https://zh.wikipedia.org/wiki/%E7%84%A1%E9%9A%9C%E7%A4%99%E7%92%B0%E5%A2%83

https://developer.mozilla.org/zh-CN/docs/Web/Accessibility

---------

`更友好` 建议改为 `有帮助`

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "<strong>Note</strong><br>在后面的应用可访问性课程中我们会接触到更多新的 HTML5 标记，以及明白它们的用处。",
Note 是要翻译的。`注意：`

-----------

这里的“可访问性”也要改。wiki 可能也需要同步更新

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "用 <code>img</code> 标签来为你的网站添加图片，其中 <code>src</code> 属性指向一个图片的具体地址。",
`具体地址` => `地址`
或者干脆就用 URL 也行。后文你用的是 “URL 地址”

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "所有的 <code>img</code> 标签必须有 <code>alt</code> 属性，<code>alt</code> 属性的文本是当图片无法加载时显示的替代文本，对于通过屏幕阅读器来浏览网页的用户非常重要。",
`……图片无法加载时显示的替代文本，对于通过屏幕阅读器来浏览网页的用户非常重要。` =>
`……图片无法加载时显示的替代文本。另一方面，这对通过屏幕阅读器来浏览网页的视障用户来说也是非常重要的。`

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "现在设置 <code>src</code> 属性指向一个 url 地址：",
`一个` => `这个`

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "锚点需要一个<code>href</code>属性指向目的地，它还需要有锚点文本，例如：",
code block 两边加上空格

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
>          "<code>&#60;a href=\"https://freecodecamp.org\">this links to freecodecamp.org&#60;/a&#62;</code>",
这一行和下一行，要不要换成中文版的链接？后续应该需要换的。

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +          "testString": "assert(code.match(/<\\/a>/g) && code.match(/<\\/a>/g).length === code.match(/<a/g).length, '确保<code>a</code> 标签有结束标记。');"
空格

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "通过给 <code>href</code> 属性赋值为一个哈希符号 <code>#</code> 加上你想跳转的标签对应的 <code>id</code> 属性值来创建一个内部链接。 <code>id</code> 是用来描述页面唯一标签的属性。",
`哈希符号` => `井号`
hash symbol 是英文中对井号的称呼，有时也叫 hash tag（twitter 上）。此外还有 pound key（电话上的井号），和 number（比如 `#1` 念 number 1）。这些都是井号

--------

删掉句号之后多余的空格。

--------

第一句意思没错，不过太长，没有断句。。建议换一下表达方式。

--------

`<code>id</code> 是用来描述页面唯一标签的属性。` => `<code>id</code> 是用来描述网页元素的一个属性，它的值在整个页面中唯一。`

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "当用户点击了 <code>Contacts</code>链接，页面就会跳转到网页的 <b>Contacts</b> 区域。",
空格。

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "移除 <code>target=\"_blank\"</code> 属性避免点击链接会跳转到新的标签页。",
`跳转到` => `打开`

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "通常，文本是被包裹在 <code>p</code> 标签内:<br> <code>&#60;p&#62; Here's a ... for you to follow. &#60;/p&#62;</code>",
冒号应为全角

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "接下来是 <code>anchor</code> 标签 <code>&#60;a&#62;</code> (需要结束标记 <code>&#60;/a&#62;</code>):<br>  <code>&#60;a&#62; ... &#60;/a&#62;</code>",
括号应为全角

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "<code>target</code> 是锚点标签的一个属性，它指定了会以什么方式来打开链接。 属性值 <code>\"_blank\"</code> 指定了会新开一个标签页来打开链接",
删掉句号之后多余的空格。

`指定了会新开一个标签页来打开链接` => `的意思是链接会在新标签页打开`

2018-07-21 06:50 UTC, S1ngS1ng commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "现在用一个新的 <code>p</code> 标签来包裹现存的 <code>a</code> 标签（紧挨着 <code>main</code>标签)。新段落的文本为：View more cat photos，其中 \"cat photos\" 是一个链接，其他是纯文本。"
这里的`紧挨着`可能会造成歧义。我试了下，必须放到 `main` 之后才行，原文也是这么描述的。改下吧。

2018-07-21 15:59 UTC, huluoyang commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "欢迎来到 FreeCodeCamp 的 HTML 编码挑战，这些挑战将会帮助你逐步掌握 web 开发。",
多谢指正

2018-07-21 16:01 UTC, huluoyang commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "Web开发者通常用 <a href='http://www.ruanyifeng.com/blog/2009/04/lorem_ipsum.html'>lorem ipsum text</a> 来做占位符，占位符就是占着位置的一些文字，没有实际意义。",
开发者有很多类型，FCC 针对的是 Web 开发者。
wikipedia 国内被墙，所以特意找的阮一峰老师博客。

2018-07-21 16:06 UTC, huluoyang commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "移除 <code>target=\"_blank\"</code> 属性避免点击链接会跳转到新的标签页。",
OK

2018-07-21 16:07 UTC, huluoyang commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "通常，文本是被包裹在 <code>p</code> 标签内:<br> <code>&#60;p&#62; Here's a ... for you to follow. &#60;/p&#62;</code>",
恩，确实，我也犯错了。

2018-07-21 16:10 UTC, huluoyang commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "你看到代码编辑器中的 <code>&#60;h1&#62;Hello&#60;/h1&#62;</code> 了吗? 那就是一个 HTML 标签，<code>h1</code> 是 <code>header1</code> 的简写，意思是主标题。",
多谢指正，我是望文生义了。

2018-07-21 16:10 UTC, huluoyang commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "HTML 是英文 Hyper Text Markup Language(超文本标记语言)的缩写。首先，使用 HTML 来制作一个简单的网页，你可以直接在本网页内置的代码编辑器中编辑代码。"
是的，应该是后者。

2018-07-21 22:56 UTC, huluoyang commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "<strong>Note</strong><br>在后面的应用可访问性课程中我们会接触到更多新的 HTML5 标记，以及明白它们的用处。",
恩，确实，可访问性 只是直译。

2018-07-21 23:02 UTC, huluoyang commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "用 <code>img</code> 标签来为你的网站添加图片，其中 <code>src</code> 属性指向一个图片的具体地址。",
是的，这次突然插入了 URL 概念，但前面又没介绍过，干脆统一改成地址。

2018-07-21 23:06 UTC, huluoyang commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "所有的 <code>img</code> 标签必须有 <code>alt</code> 属性，<code>alt</code> 属性的文本是当图片无法加载时显示的替代文本，对于通过屏幕阅读器来浏览网页的用户非常重要。",
……图片无法加载时显示的替代文本，这对于通过屏幕阅读器来浏览网页的用户非常重要。

通过屏幕阅读器来浏览网页的自然是视障用户，不用强调这个词。
另一方面啰嗦了，加个代词：这，就挺好，阅读流畅。

2018-07-21 23:11 UTC, huluoyang commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "现在设置 <code>src</code> 属性指向一个 url 地址：",
恩，忽略了。

2018-07-21 23:11 UTC, huluoyang commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "锚点需要一个<code>href</code>属性指向目的地，它还需要有锚点文本，例如：",
恩，星星是强迫症患者的福音。^_^

2018-07-21 23:24 UTC, huluoyang commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "通过给 <code>href</code> 属性赋值为一个哈希符号 <code>#</code> 加上你想跳转的标签对应的 <code>id</code> 属性值来创建一个内部链接。 <code>id</code> 是用来描述页面唯一标签的属性。",
我看中文的课程看多了，全都说的是哈希符号，搞得很高大上，其实就是就是个象形字。
因为只有在系统、后端中，哈希才有它真正的意义。

2018-07-21 23:33 UTC, huluoyang commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "通过给 <code>href</code> 属性赋值为一个哈希符号 <code>#</code> 加上你想跳转的标签对应的 <code>id</code> 属性值来创建一个内部链接。 <code>id</code> 是用来描述页面唯一标签的属性。",
确实，拆分后，读起来朗朗上口，之前有点拗口难以理解。

2018-07-22 09:08 UTC, huluoyang commented on 01-responsive-web-design/basic-html-and-html5.json
> +        "接下来是 <code>anchor</code> 标签 <code>&#60;a&#62;</code> (需要结束标记 <code>&#60;/a&#62;</code>):<br>  <code>&#60;a&#62; ... &#60;/a&#62;</code>",
火眼金睛 ^_^

2018-07-22 09:22 UTC, huluoyang commented
修正了之前的错误，增加了新的需要翻译的 md 文档，先 Merge 进仓库，更新 Wiki。

2018-07-22 09:23 UTC, merged